#!/bin/sh
# install.sh — put `arxa` on PATH, from any checkout, on any machine.
#
# Replaces the hand-written machine-bound shim that hard-coded one Mac's
# absolute path. This script derives the repo root from its OWN location, so
# it works in any clone, worktree, or relocated checkout.
#
# What it does:
#   1. resolves the repo root from this script's real path
#   2. `dart pub get` in arxa/
#   3. AOT-compiles the CLI to <repo>/.build/arxa   (gitignored)
#   4. writes a small wrapper onto PATH that execs that binary
#
# Why AOT and not `dart run`: measured on this repo, `dart run` costs ~1.42s
# per invocation even warm; the AOT binary costs ~0.01s. Agent hooks fire on
# every tool call, so the 142x difference is the difference between a usable
# gate and an unusable one.
#
# Why the binary lives INSIDE the repo: the designer resolves its runtime
# assets (skills/arxa-designer/runtime/...) by walking up from the running
# executable to the dir holding config/arxa.config.json. A binary outside
# the tree silently loses those assets — `arxa design doctor` reports them
# MISSING. Keeping it at <repo>/.build/ keeps that walk working.
#
# Usage:
#   ./install.sh                    # build + install wrapper (idempotent)
#   ./install.sh --prefix ~/bin     # choose the PATH dir
#   ./install.sh --no-build         # rewrite the wrapper only
#   ./install.sh --check            # report state, change nothing
set -eu

# ── locate the repo from this script, following symlinks ─────────────────────
script="$0"
while [ -L "$script" ]; do
  link=$(readlink "$script")
  case "$link" in
    /*) script="$link" ;;
    *)  script="$(dirname "$script")/$link" ;;
  esac
done
REPO=$(CDPATH= cd -- "$(dirname -- "$script")" && pwd -P)

if [ ! -f "$REPO/config/arxa.config.json" ]; then
  echo "install.sh: $REPO does not look like an arxa checkout" >&2
  echo "  (expected config/arxa.config.json)" >&2
  exit 1
fi

PREFIX=""
DO_BUILD=1
CHECK_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="${2:-}"; shift 2 ;;
    --prefix=*) PREFIX="${1#--prefix=}"; shift ;;
    --no-build) DO_BUILD=0; shift ;;
    --check) CHECK_ONLY=1; shift ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "install.sh: unknown option $1" >&2; exit 2 ;;
  esac
done

BUILD_DIR="$REPO/.build"
BIN="$BUILD_DIR/arxa"

# ── pick a PATH dir ──────────────────────────────────────────────────────────
if [ -z "$PREFIX" ]; then
  for cand in "$HOME/.local/bin" "$HOME/bin" "$HOME/.pub-cache/bin"; do
    case ":$PATH:" in *":$cand:"*) PREFIX="$cand"; break ;; esac
  done
  [ -z "$PREFIX" ] && PREFIX="$HOME/.local/bin"
fi
WRAPPER="$PREFIX/arxa"

if [ "$CHECK_ONLY" -eq 1 ]; then
  echo "repo     $REPO"
  echo "binary   $BIN $([ -x "$BIN" ] && echo '(present)' || echo '(MISSING)')"
  echo "wrapper  $WRAPPER $([ -f "$WRAPPER" ] && echo '(present)' || echo '(MISSING)')"
  echo "resolves $(command -v arxa 2>/dev/null || echo '(not on PATH)')"
  exit 0
fi

command -v dart >/dev/null 2>&1 || {
  echo "install.sh: dart not found on PATH — install the Dart SDK first" >&2
  exit 1
}

# ── build ────────────────────────────────────────────────────────────────────
if [ "$DO_BUILD" -eq 1 ]; then
  echo "==> dart pub get"
  ( cd "$REPO/arxa" && dart pub get >/dev/null )
  echo "==> compiling arxa (AOT)"
  mkdir -p "$BUILD_DIR"
  # Compile to a unique temp name, then rename: `mv` on the same filesystem is
  # atomic, so two concurrent installs/rebuilds can never expose a half-written
  # binary to a third process that is trying to run it.
  tmp="$BUILD_DIR/.arxa.$$"
  ( cd "$REPO/arxa" && dart compile exe bin/arxa.dart -o "$tmp" >/dev/null )
  mv -f "$tmp" "$BIN"
  chmod +x "$BIN"
  echo "    $BIN ($(du -h "$BIN" | cut -f1))"
fi

# ── cross-harness skill discovery ────────────────────────────────────────────
# The 13 skills live in skills/. Claude Code finds them via .claude/skills, but
# dsh scans <root>/.dsh/skills and <root>/.agents/skills, and Pi scans
# <root>/.pi/skills and <root>/.agents/skills — none of which is .claude/skills.
# One relative symlink at .agents/skills therefore serves BOTH dsh and Pi. It is
# committed, so a fresh clone works with no setup; this heals a checkout that
# lost it (e.g. a filesystem without symlink support).
if [ ! -e "$REPO/.agents/skills" ]; then
  mkdir -p "$REPO/.agents"
  ln -sfn ../skills "$REPO/.agents/skills"
  echo "==> linked .agents/skills -> skills (dsh + Pi skill discovery)"
fi

# ── wrapper ──────────────────────────────────────────────────────────────────
mkdir -p "$PREFIX"
cat > "$WRAPPER" <<WRAPPER_EOF
#!/bin/sh
# arxa — generated by arxa/install.sh. Do not edit; re-run install.sh.
# Repo baked at install time (derived, never hand-typed):
REPO='$REPO'
WRAPPER_EOF
cat >> "$WRAPPER" <<'WRAPPER_EOF'
BIN="$REPO/.build/arxa"

# Rebuild from source when a .dart file is newer than the binary. `-print -quit`
# short-circuits on the first hit, so this costs <10ms over ~130 files.
stale() {
  [ -n "$(find "$REPO/arxa/bin" "$REPO/arxa/lib" -name '*.dart' \
      -newer "$BIN" -print -quit 2>/dev/null)" ]
}
build() {
  tmp="$REPO/.build/.arxa.$$"
  mkdir -p "$REPO/.build"
  ( cd "$REPO/arxa" && dart compile exe bin/arxa.dart -o "$tmp" >&2 ) || return 1
  mv -f "$tmp" "$BIN"
}

if [ ! -x "$BIN" ]; then
  if [ -n "${ARXA_FAST:-}" ]; then
    # Hook context: never pay a ~4s compile inside someone's tool call. Fail
    # loudly on stderr instead of silently doing nothing.
    echo "[arxa] binary missing at $BIN — run: $REPO/install.sh" >&2
    exit 127
  fi
  echo "[arxa] building (first run)..." >&2
  build || exit 1
elif stale; then
  if [ -n "${ARXA_FAST:-}" ]; then
    # Announce staleness rather than silently running old code — a silently
    # stale binary is a correctness hazard, not a convenience one.
    echo "[arxa] WARNING: binary is STALE (source newer). Run: $REPO/install.sh" >&2
  else
    echo "[arxa] source changed — rebuilding..." >&2
    build || exit 1
  fi
fi

exec "$BIN" "$@"
WRAPPER_EOF
chmod +x "$WRAPPER"
echo "==> wrapper $WRAPPER"

# ── report PATH truth (do not silently shadow) ───────────────────────────────
resolved=$(command -v arxa 2>/dev/null || true)
if [ "$resolved" != "$WRAPPER" ] && [ -n "$resolved" ]; then
  echo
  echo "!! PATH still resolves 'arxa' to:  $resolved"
  echo "   not the wrapper just written to: $WRAPPER"
  echo "   That older entry shadows this install. Remove it, or re-run with"
  echo "   --prefix \"\$(dirname \"$resolved\")\" to overwrite it in place."
elif [ -z "$resolved" ]; then
  echo
  echo "!! $PREFIX is not on your PATH. Add it:"
  echo "   export PATH=\"$PREFIX:\$PATH\""
else
  echo "==> arxa resolves to $resolved"
fi
