/// Generates the cairn client schema from [ArxaKitTableSchema] descriptors,
/// plus the server-side CRDT env declaration snippet. Pure Dart — like the
/// kit/data emitters, it runs under `dart run` outside the Flutter toolchain.
///
/// Triple consistency: a `crdt:`-flagged [ArxaKitColumn] must match (1) the
/// client open call's `orSetTables` / `counterTables`, (2) the server env
/// `CAIRN_OR_SET_COLUMNS` / `CAIRN_COUNTER_COLUMNS`, and (3) this schema —
/// the backend validates (1)↔(3) at boot; [emitServerCrdtEnv] generates (2)
/// so none of the three is hand-copied.
library;

import 'package:cairn_flutter/cairn_flutter.dart';
import 'package:arxa_kit_data/arxa_kit_data.dart';

class CairnSchemaEmitter {
  /// The attachments metadata table (ADR-0034) as a client schema declaration.
  /// The backend appends this to the emitted schema when storage is enabled —
  /// apps never declare it by hand. Column names mirror cairn's
  /// `AttachmentSchema` contract exactly; `size`/`timestamp` are INTEGER,
  /// everything else TEXT.
  static CairnTable attachmentsTable() => const CairnTable(
        name: AttachmentSchema.table,
        primaryKey: [AttachmentSchema.colId],
        columns: [
          CairnColumn.text(AttachmentSchema.colId),
          CairnColumn.text(AttachmentSchema.colFilename),
          CairnColumn.integer(AttachmentSchema.colSize),
          CairnColumn.text(AttachmentSchema.colMediaType),
          CairnColumn.text(AttachmentSchema.colState),
          CairnColumn.integer(AttachmentSchema.colTimestamp),
        ],
      );

  /// The cairn client schema for [schemas] — one [CairnTable] per kit table,
  /// `id` as the primary key, each column mapped to the affinity the WS2
  /// read-views actually serve (the views are `json_extract` projections:
  /// booleans arrive as 0/1 INTEGER, nested JSON arrives as TEXT).
  CairnSchema schemaFor(List<ArxaKitTableSchema> schemas) => CairnSchema(
        tables: [
          for (final schema in schemas)
            CairnTable(
              name: schema.table,
              primaryKey: [schema.idColumn.name],
              columns: [
                for (final column in schema.columns)
                  CairnColumn(
                    name: column.name,
                    affinity: _affinity(column.type),
                  ),
              ],
            ),
        ],
      );

  String _affinity(ArxaKitColumnType type) => switch (type) {
        ArxaKitColumnType.id => 'TEXT',
        ArxaKitColumnType.text => 'TEXT',
        ArxaKitColumnType.integer => 'INTEGER',
        ArxaKitColumnType.real => 'REAL',
        ArxaKitColumnType.boolean => 'INTEGER',
        ArxaKitColumnType.timestamptz => 'TEXT',
        ArxaKitColumnType.jsonb => 'TEXT',
        ArxaKitColumnType.reference => 'TEXT',
      };

  /// The server-side CRDT declaration for [schemas], as shell-env lines an
  /// operator pastes into the cairn server's environment. Deterministic:
  /// both declarations are always present (empty when no column is flagged),
  /// entries sorted so a diff between generations shows exactly what changed.
  ///
  /// [includeAttachments] appends the write-allowlist reminder for the
  /// attachments metadata table — blob metadata writes go through the same
  /// outbox as business writes, so the server must accept them.
  String emitServerCrdtEnv(
    List<ArxaKitTableSchema> schemas, {
    bool includeAttachments = false,
  }) {
    final counters = <String>[];
    final orSets = <String>[];
    final counterTables = <String>{};
    final orSetTables = <String>{};
    for (final schema in schemas) {
      for (final column in schema.columns) {
        switch (column.crdt) {
          case ArxaKitCrdtTier.counter:
            counters.add('${schema.table}:${column.name}');
            counterTables.add(schema.table);
          case ArxaKitCrdtTier.orSet:
            orSets.add('${schema.table}:${column.name}');
            orSetTables.add(schema.table);
          case null:
            break;
        }
      }
    }
    final dual = counterTables.intersection(orSetTables);
    if (dual.isNotEmpty) {
      throw StateError(
        'CairnSchemaEmitter: table "${dual.first}" is flagged for BOTH tiers '
        '— the engine merges one CRDT tier per table (or-set wins the first '
        'branch checked, silently dropping the counter tag), so emitting '
        'this env would bake in a misconfiguration; tag each table with '
        'exactly one tier.',
      );
    }
    counters.sort();
    orSets.sort();
    return '# Generated by arxa_kit_cairn (CairnSchemaEmitter). '
        'Do not edit by hand.\n'
        '# Must match the client config (ArxaKitCairnConfig.orSetTables /\n'
        '# .counterTables) and the schema crdt flags exactly.\n'
        '# Server DDL prerequisites (cairn write-back binds these exactly):\n'
        '# - pk columns must be `uuid`, not `text` — write_back from_scalar\n'
        '#   binds UUID-parsable pks as SqlValue::Uuid; kit canonical ids are\n'
        '#   v5 UUIDs, so a text pk fails the bind with "error serializing\n'
        '#   parameter 0".\n'
        '# - every synced table needs ALTER TABLE <t> REPLICA IDENTITY FULL —\n'
        '#   else live DELETEs carry only PK columns and delete fan-out is\n'
        '#   silently dropped (the server boot check names this fix verbatim).\n'
        'CAIRN_COUNTER_COLUMNS=${counters.join(',')}\n'
        'CAIRN_OR_SET_COLUMNS=${orSets.join(',')}\n'
        '${includeAttachments ? '# Storage is enabled: attachment metadata writes go through the\n'
            '# same outbox as business writes — the server write allowlist\n'
            '# CAIRN_WRITE_TABLES must include: attachments\n' : ''}';
  }
}
