// Mocks generated by Mockito 5.4.6 from annotations
// in appbox_kit_showcase_app/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i13;

import 'package:appbox_kit_data/appbox_kit_data.dart' as _i3;
import 'package:appbox_kit_media/appbox_kit_media.dart' as _i20;
import 'package:appbox_kit_showcase_app/data/models/showcase_notes_models/showcase_note_attachment_model.dart'
    as _i17;
import 'package:appbox_kit_showcase_app/data/models/showcase_notes_models/showcase_note_folder_model.dart'
    as _i5;
import 'package:appbox_kit_showcase_app/data/models/showcase_notes_models/showcase_note_model.dart'
    as _i4;
import 'package:appbox_kit_showcase_app/services/showcase_notes_services/adapters/showcase_notes_media_adapter_service.dart'
    as _i19;
import 'package:appbox_kit_showcase_app/services/showcase_notes_services/facades/showcase_notes_facade_service.dart'
    as _i16;
import 'package:flutter/material.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:rxdart/rxdart.dart' as _i7;
import 'package:stacked/stacked.dart' as _i2;
import 'package:stacked_services/src/bottom_sheet/bottom_sheet_service.dart'
    as _i11;
import 'package:stacked_services/src/dialog/dialog_service.dart' as _i14;
import 'package:stacked_services/src/models/overlay_request.dart' as _i15;
import 'package:stacked_services/src/models/overlay_response.dart' as _i12;
import 'package:stacked_services/src/navigation/router_service.dart' as _i8;
import 'package:ui_library/ui_library.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRootStackRouter_0 extends _i1.SmartFake
    implements _i2.RootStackRouter {
  _FakeRootStackRouter_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteData_1 extends _i1.SmartFake implements _i2.RouteData {
  _FakeRouteData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoutingController_2 extends _i1.SmartFake
    implements _i2.RoutingController {
  _FakeRoutingController_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitAuthService_3 extends _i1.SmartFake
    implements _i3.KitAuthService {
  _FakeKitAuthService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShowcaseNoteModel_4 extends _i1.SmartFake
    implements _i4.ShowcaseNoteModel {
  _FakeShowcaseNoteModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeShowcaseNoteFolderModel_5 extends _i1.SmartFake
    implements _i5.ShowcaseNoteFolderModel {
  _FakeShowcaseNoteFolderModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitRepository_6<T1> extends _i1.SmartFake
    implements _i3.KitRepository<T1> {
  _FakeKitRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKitActionBuilder_7<T1> extends _i1.SmartFake
    implements _i6.KitActionBuilder<T1> {
  _FakeKitActionBuilder_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStream_8<T> extends _i1.SmartFake
    implements _i7.ValueStream<T> {
  _FakeValueStream_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBehaviorSubject_9<T> extends _i1.SmartFake
    implements _i7.BehaviorSubject<T> {
  _FakeBehaviorSubject_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i8.RouterService {
  @override
  _i2.RootStackRouter get router => (super.noSuchMethod(
        Invocation.getter(#router),
        returnValue: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
        returnValueForMissingStub: _FakeRootStackRouter_0(
          this,
          Invocation.getter(#router),
        ),
      ) as _i2.RootStackRouter);

  @override
  List<_i2.StackedPage<dynamic>> get stack => (super.noSuchMethod(
        Invocation.getter(#stack),
        returnValue: <_i2.StackedPage<dynamic>>[],
        returnValueForMissingStub: <_i2.StackedPage<dynamic>>[],
      ) as List<_i2.StackedPage<dynamic>>);

  @override
  _i2.RouteData get topRoute => (super.noSuchMethod(
        Invocation.getter(#topRoute),
        returnValue: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
        returnValueForMissingStub: _FakeRouteData_1(
          this,
          Invocation.getter(#topRoute),
        ),
      ) as _i2.RouteData);

  @override
  set router(_i2.RootStackRouter? value) => super.noSuchMethod(
        Invocation.setter(
          #router,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setRouter(_i2.RootStackRouter? router) => super.noSuchMethod(
        Invocation.method(
          #setRouter,
          [router],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<dynamic> navigateTo(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<dynamic>.value(),
        returnValueForMissingStub: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<void> navigateToPath({
    required String? path,
    bool? includePrefixMatches = false,
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToPath,
          [],
          {
            #path: path,
            #includePrefixMatches: includePrefixMatches,
            #onFailure: onFailure,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<T?> navigateWithTransition<T extends Object?>(
    _i10.Widget? widget, {
    _i10.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i9.Future<T?>.value(),
        returnValueForMissingStub: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);

  @override
  _i9.Future<T?> replaceWith<T extends Object?>(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<T?>.value(),
        returnValueForMissingStub: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);

  @override
  _i9.Future<void> clearStackAndShow(
    _i2.PageRouteInfo<dynamic>? route, {
    _i2.OnNavigationFailure? onFailure,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [route],
          {#onFailure: onFailure},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearStackAndShowView(
    _i10.Widget? widget, {
    _i10.RouteTransitionsBuilder? transitionBuilder,
    bool? fullscreenDialog = false,
    Duration? transitionDuration = const Duration(milliseconds: 300),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [widget],
          {
            #transitionBuilder: transitionBuilder,
            #fullscreenDialog: fullscreenDialog,
            #transitionDuration: transitionDuration,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void popForced<T extends Object?>([T? result]) => super.noSuchMethod(
        Invocation.method(
          #popForced,
          [result],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<bool> pop<T extends Object?>([T? result]) => (super.noSuchMethod(
        Invocation.method(
          #pop,
          [result],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  void back<T extends Object?>({T? result}) => super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {#result: result},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.RoutingController topMostRouter({bool? ignorePagelessRoutes = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #topMostRouter,
          [],
          {#ignorePagelessRoutes: ignorePagelessRoutes},
        ),
        returnValue: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
        returnValueForMissingStub: _FakeRoutingController_2(
          this,
          Invocation.method(
            #topMostRouter,
            [],
            {#ignorePagelessRoutes: ignorePagelessRoutes},
          ),
        ),
      ) as _i2.RoutingController);

  @override
  _i9.Future<T?> pushNativeRoute<T extends Object?>(_i10.Route<T>? route) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNativeRoute,
          [route],
        ),
        returnValue: _i9.Future<T?>.value(),
        returnValueForMissingStub: _i9.Future<T?>.value(),
      ) as _i9.Future<T?>);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i11.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i11.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i12.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = 'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
    double? elevation = 1.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
            #elevation: elevation,
          },
        ),
        returnValue: _i9.Future<_i12.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i12.SheetResponse<dynamic>?>.value(),
      ) as _i9.Future<_i12.SheetResponse<dynamic>?>);

  @override
  _i9.Future<_i12.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i13.Color? barrierColor = const _i13.Color(2315255808),
    double? elevation = 1.0,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = '',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #elevation: elevation,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i9.Future<_i12.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i12.SheetResponse<T>?>.value(),
      ) as _i9.Future<_i12.SheetResponse<T>?>);

  @override
  void completeSheet(_i12.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i14.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i14.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i10.Widget Function(
      _i10.BuildContext,
      _i15.DialogRequest<dynamic>,
      dynamic Function(_i12.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i12.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i13.Color? cancelTitleColor,
    String? buttonTitle = 'Ok',
    _i13.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i10.RouteSettings? routeSettings,
    _i10.GlobalKey<_i10.NavigatorState>? navigatorKey,
    _i14.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i12.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i12.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i12.DialogResponse<dynamic>?>);

  @override
  _i9.Future<_i12.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i13.Color? barrierColor = const _i13.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = '',
    bool? useSafeArea = true,
    _i10.RouteSettings? routeSettings,
    _i10.GlobalKey<_i10.NavigatorState>? navigatorKey,
    _i10.RouteTransitionsBuilder? transitionBuilder,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #routeSettings: routeSettings,
            #navigatorKey: navigatorKey,
            #transitionBuilder: transitionBuilder,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i9.Future<_i12.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i9.Future<_i12.DialogResponse<T>?>.value(),
      ) as _i9.Future<_i12.DialogResponse<T>?>);

  @override
  _i9.Future<_i12.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = 'Cancel',
    _i13.Color? cancelTitleColor,
    String? confirmationTitle = 'Ok',
    _i13.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i10.RouteSettings? routeSettings,
    _i14.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #routeSettings: routeSettings,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i9.Future<_i12.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i12.DialogResponse<dynamic>?>.value(),
      ) as _i9.Future<_i12.DialogResponse<dynamic>?>);

  @override
  void completeDialog(_i12.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShowcaseNotesFacadeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowcaseNotesFacadeService extends _i1.Mock
    implements _i16.ShowcaseNotesFacadeService {
  @override
  _i9.Stream<_i3.KitAuthSession?> get session$ => (super.noSuchMethod(
        Invocation.getter(#session$),
        returnValue: _i9.Stream<_i3.KitAuthSession?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i3.KitAuthSession?>.empty(),
      ) as _i9.Stream<_i3.KitAuthSession?>);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.KitAuthService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeKitAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeKitAuthService_3(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.KitAuthService);

  @override
  _i9.Stream<List<_i5.ShowcaseNoteFolderModel>> folders$(String? owner) =>
      (super.noSuchMethod(
        Invocation.method(
          #folders$,
          [owner],
        ),
        returnValue: _i9.Stream<List<_i5.ShowcaseNoteFolderModel>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i5.ShowcaseNoteFolderModel>>.empty(),
      ) as _i9.Stream<List<_i5.ShowcaseNoteFolderModel>>);

  @override
  _i9.Stream<_i16.ShowcaseNotesOverview> overview$(String? owner) =>
      (super.noSuchMethod(
        Invocation.method(
          #overview$,
          [owner],
        ),
        returnValue: _i9.Stream<_i16.ShowcaseNotesOverview>.empty(),
        returnValueForMissingStub:
            _i9.Stream<_i16.ShowcaseNotesOverview>.empty(),
      ) as _i9.Stream<_i16.ShowcaseNotesOverview>);

  @override
  _i9.Stream<_i16.ShowcaseNotesAdminOverview> adminOverview$() =>
      (super.noSuchMethod(
        Invocation.method(
          #adminOverview$,
          [],
        ),
        returnValue: _i9.Stream<_i16.ShowcaseNotesAdminOverview>.empty(),
        returnValueForMissingStub:
            _i9.Stream<_i16.ShowcaseNotesAdminOverview>.empty(),
      ) as _i9.Stream<_i16.ShowcaseNotesAdminOverview>);

  @override
  _i9.Stream<List<_i4.ShowcaseNoteModel>> notesIn$(
    String? owner, {
    String? folderId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #notesIn$,
          [owner],
          {#folderId: folderId},
        ),
        returnValue: _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
      ) as _i9.Stream<List<_i4.ShowcaseNoteModel>>);

  @override
  _i9.Stream<List<_i4.ShowcaseNoteModel>> trash$(String? owner) =>
      (super.noSuchMethod(
        Invocation.method(
          #trash$,
          [owner],
        ),
        returnValue: _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
      ) as _i9.Stream<List<_i4.ShowcaseNoteModel>>);

  @override
  _i9.Stream<_i4.ShowcaseNoteModel?> note$(String? id) => (super.noSuchMethod(
        Invocation.method(
          #note$,
          [id],
        ),
        returnValue: _i9.Stream<_i4.ShowcaseNoteModel?>.empty(),
        returnValueForMissingStub: _i9.Stream<_i4.ShowcaseNoteModel?>.empty(),
      ) as _i9.Stream<_i4.ShowcaseNoteModel?>);

  @override
  _i9.Stream<List<_i4.ShowcaseNoteModel>> search$(
    String? owner,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #search$,
          [
            owner,
            query,
          ],
        ),
        returnValue: _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
        returnValueForMissingStub:
            _i9.Stream<List<_i4.ShowcaseNoteModel>>.empty(),
      ) as _i9.Stream<List<_i4.ShowcaseNoteModel>>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> createNote(
    String? owner,
    String? folderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [
            owner,
            folderId,
          ],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #createNote,
            [
              owner,
              folderId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #createNote,
            [
              owner,
              folderId,
            ],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> saveBody(
    _i4.ShowcaseNoteModel? note,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBody,
          [
            note,
            body,
          ],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #saveBody,
            [
              note,
              body,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #saveBody,
            [
              note,
              body,
            ],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> togglePin(_i4.ShowcaseNoteModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePin,
          [note],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #togglePin,
            [note],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #togglePin,
            [note],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> addAttachment(
    _i4.ShowcaseNoteModel? note,
    _i17.ShowcaseNoteAttachmentModel? attachment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAttachment,
          [
            note,
            attachment,
          ],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #addAttachment,
            [
              note,
              attachment,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #addAttachment,
            [
              note,
              attachment,
            ],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> removeAttachment(
    _i4.ShowcaseNoteModel? note,
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeAttachment,
          [
            note,
            attachmentId,
          ],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #removeAttachment,
            [
              note,
              attachmentId,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #removeAttachment,
            [
              note,
              attachmentId,
            ],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> moveToTrash(_i4.ShowcaseNoteModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveToTrash,
          [note],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #moveToTrash,
            [note],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #moveToTrash,
            [note],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<_i4.ShowcaseNoteModel> restore(_i4.ShowcaseNoteModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #restore,
          [note],
        ),
        returnValue:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #restore,
            [note],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i4.ShowcaseNoteModel>.value(_FakeShowcaseNoteModel_4(
          this,
          Invocation.method(
            #restore,
            [note],
          ),
        )),
      ) as _i9.Future<_i4.ShowcaseNoteModel>);

  @override
  _i9.Future<void> deletePermanently(_i4.ShowcaseNoteModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePermanently,
          [note],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> emptyTrash(String? owner) => (super.noSuchMethod(
        Invocation.method(
          #emptyTrash,
          [owner],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.ShowcaseNoteFolderModel> createFolder(
    String? owner,
    String? name, {
    required int? sortOrder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFolder,
          [
            owner,
            name,
          ],
          {#sortOrder: sortOrder},
        ),
        returnValue: _i9.Future<_i5.ShowcaseNoteFolderModel>.value(
            _FakeShowcaseNoteFolderModel_5(
          this,
          Invocation.method(
            #createFolder,
            [
              owner,
              name,
            ],
            {#sortOrder: sortOrder},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i5.ShowcaseNoteFolderModel>.value(
                _FakeShowcaseNoteFolderModel_5(
          this,
          Invocation.method(
            #createFolder,
            [
              owner,
              name,
            ],
            {#sortOrder: sortOrder},
          ),
        )),
      ) as _i9.Future<_i5.ShowcaseNoteFolderModel>);

  @override
  _i9.Future<_i5.ShowcaseNoteFolderModel> renameFolder(
    _i5.ShowcaseNoteFolderModel? folder,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFolder,
          [
            folder,
            name,
          ],
        ),
        returnValue: _i9.Future<_i5.ShowcaseNoteFolderModel>.value(
            _FakeShowcaseNoteFolderModel_5(
          this,
          Invocation.method(
            #renameFolder,
            [
              folder,
              name,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i5.ShowcaseNoteFolderModel>.value(
                _FakeShowcaseNoteFolderModel_5(
          this,
          Invocation.method(
            #renameFolder,
            [
              folder,
              name,
            ],
          ),
        )),
      ) as _i9.Future<_i5.ShowcaseNoteFolderModel>);

  @override
  _i9.Future<void> deleteFolder(_i5.ShowcaseNoteFolderModel? folder) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFolder,
          [folder],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i3.KitRepository<T> repository<T>() => (super.noSuchMethod(
        Invocation.method(
          #repository,
          [],
        ),
        returnValue: _FakeKitRepository_6<T>(
          this,
          Invocation.method(
            #repository,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeKitRepository_6<T>(
          this,
          Invocation.method(
            #repository,
            [],
          ),
        ),
      ) as _i3.KitRepository<T>);

  @override
  S registerSubject<S extends _i7.Subject<dynamic>>(S? subject) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerSubject,
          [subject],
        ),
        returnValue: _i18.dummyValue<S>(
          this,
          Invocation.method(
            #registerSubject,
            [subject],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<S>(
          this,
          Invocation.method(
            #registerSubject,
            [subject],
          ),
        ),
      ) as S);

  @override
  _i6.KitActionBuilder<T> mutate<T>(
    _i9.FutureOr<T> Function()? operation, {
    String? name,
    String? entity,
    String? error,
    String? success,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #mutate,
          [operation],
          {
            #name: name,
            #entity: entity,
            #error: error,
            #success: success,
          },
        ),
        returnValue: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #mutate,
            [operation],
            {
              #name: name,
              #entity: entity,
              #error: error,
              #success: success,
            },
          ),
        ),
        returnValueForMissingStub: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #mutate,
            [operation],
            {
              #name: name,
              #entity: entity,
              #error: error,
              #success: success,
            },
          ),
        ),
      ) as _i6.KitActionBuilder<T>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i6.KitActionBuilder<T> action<T>(
    String? name,
    _i9.FutureOr<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #action,
          [
            name,
            operation,
          ],
        ),
        returnValue: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #action,
            [
              name,
              operation,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #action,
            [
              name,
              operation,
            ],
          ),
        ),
      ) as _i6.KitActionBuilder<T>);

  @override
  void watch(
    String? name, {
    required List<_i9.Stream<dynamic>>? streams,
    required void Function(dynamic)? callback,
    String? errorMessage,
    void Function(Object)? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #watch,
          [name],
          {
            #streams: streams,
            #callback: callback,
            #errorMessage: errorMessage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.ValueStream<_i6.KitActionState> actionState$(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #actionState$,
          [name],
        ),
        returnValue: _FakeValueStream_8<_i6.KitActionState>(
          this,
          Invocation.method(
            #actionState$,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeValueStream_8<_i6.KitActionState>(
          this,
          Invocation.method(
            #actionState$,
            [name],
          ),
        ),
      ) as _i7.ValueStream<_i6.KitActionState>);

  @override
  void disposeKitActions() => super.noSuchMethod(
        Invocation.method(
          #disposeKitActions,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ShowcaseNotesMediaAdapterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowcaseNotesMediaAdapterService extends _i1.Mock
    implements _i19.ShowcaseNotesMediaAdapterService {
  @override
  _i7.BehaviorSubject<Duration?> get recording$ => (super.noSuchMethod(
        Invocation.getter(#recording$),
        returnValue: _FakeBehaviorSubject_9<Duration?>(
          this,
          Invocation.getter(#recording$),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_9<Duration?>(
          this,
          Invocation.getter(#recording$),
        ),
      ) as _i7.BehaviorSubject<Duration?>);

  @override
  _i7.BehaviorSubject<String?> get playingAttachmentId$ => (super.noSuchMethod(
        Invocation.getter(#playingAttachmentId$),
        returnValue: _FakeBehaviorSubject_9<String?>(
          this,
          Invocation.getter(#playingAttachmentId$),
        ),
        returnValueForMissingStub: _FakeBehaviorSubject_9<String?>(
          this,
          Invocation.getter(#playingAttachmentId$),
        ),
      ) as _i7.BehaviorSubject<String?>);

  @override
  _i9.Stream<Duration> get position$ => (super.noSuchMethod(
        Invocation.getter(#position$),
        returnValue: _i9.Stream<Duration>.empty(),
        returnValueForMissingStub: _i9.Stream<Duration>.empty(),
      ) as _i9.Stream<Duration>);

  @override
  _i9.Stream<Duration?> get duration$ => (super.noSuchMethod(
        Invocation.getter(#duration$),
        returnValue: _i9.Stream<Duration?>.empty(),
        returnValueForMissingStub: _i9.Stream<Duration?>.empty(),
      ) as _i9.Stream<Duration?>);

  @override
  _i9.Stream<_i20.PlaybackState> get playerState$ => (super.noSuchMethod(
        Invocation.getter(#playerState$),
        returnValue: _i9.Stream<_i20.PlaybackState>.empty(),
        returnValueForMissingStub: _i9.Stream<_i20.PlaybackState>.empty(),
      ) as _i9.Stream<_i20.PlaybackState>);

  @override
  bool get isCameraAvailable => (super.noSuchMethod(
        Invocation.getter(#isCameraAvailable),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i9.Future<String> resolvePath(
          _i17.ShowcaseNoteAttachmentModel? attachment) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolvePath,
          [attachment],
        ),
        returnValue: _i9.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #resolvePath,
            [attachment],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #resolvePath,
            [attachment],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i17.ShowcaseNoteAttachmentModel?> pickPhoto(
          {required bool? fromCamera}) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickPhoto,
          [],
          {#fromCamera: fromCamera},
        ),
        returnValue: _i9.Future<_i17.ShowcaseNoteAttachmentModel?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i17.ShowcaseNoteAttachmentModel?>.value(),
      ) as _i9.Future<_i17.ShowcaseNoteAttachmentModel?>);

  @override
  _i9.Future<bool> startRecording() => (super.noSuchMethod(
        Invocation.method(
          #startRecording,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i17.ShowcaseNoteAttachmentModel?> stopRecording() =>
      (super.noSuchMethod(
        Invocation.method(
          #stopRecording,
          [],
        ),
        returnValue: _i9.Future<_i17.ShowcaseNoteAttachmentModel?>.value(),
        returnValueForMissingStub:
            _i9.Future<_i17.ShowcaseNoteAttachmentModel?>.value(),
      ) as _i9.Future<_i17.ShowcaseNoteAttachmentModel?>);

  @override
  _i9.Future<void> cancelRecording() => (super.noSuchMethod(
        Invocation.method(
          #cancelRecording,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> togglePlayback(
          _i17.ShowcaseNoteAttachmentModel? attachment) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePlayback,
          [attachment],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> stopPlayback() => (super.noSuchMethod(
        Invocation.method(
          #stopPlayback,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteFile(_i17.ShowcaseNoteAttachmentModel? attachment) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [attachment],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i6.KitActionBuilder<T> action<T>(
    String? name,
    _i9.FutureOr<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #action,
          [
            name,
            operation,
          ],
        ),
        returnValue: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #action,
            [
              name,
              operation,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeKitActionBuilder_7<T>(
          this,
          Invocation.method(
            #action,
            [
              name,
              operation,
            ],
          ),
        ),
      ) as _i6.KitActionBuilder<T>);

  @override
  void watch(
    String? name, {
    required List<_i9.Stream<dynamic>>? streams,
    required void Function(dynamic)? callback,
    String? errorMessage,
    void Function(Object)? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #watch,
          [name],
          {
            #streams: streams,
            #callback: callback,
            #errorMessage: errorMessage,
            #onError: onError,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.ValueStream<_i6.KitActionState> actionState$(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #actionState$,
          [name],
        ),
        returnValue: _FakeValueStream_8<_i6.KitActionState>(
          this,
          Invocation.method(
            #actionState$,
            [name],
          ),
        ),
        returnValueForMissingStub: _FakeValueStream_8<_i6.KitActionState>(
          this,
          Invocation.method(
            #actionState$,
            [name],
          ),
        ),
      ) as _i7.ValueStream<_i6.KitActionState>);

  @override
  void disposeKitActions() => super.noSuchMethod(
        Invocation.method(
          #disposeKitActions,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
