/// The palette plane (VERIFY ADDENDUM 17, grilled 2026-09-09): color
/// palettes are dial-switchable on any artifact kind that DECLARES them in
/// <artifactDir>/palettes.json — the axes plane's kind gate opens for
/// sites here, while style/theme axes stay kind:app only.
///
/// The artifact owns the application plane: base stylesheets are the
/// default palette, generated override sheets under
/// assets/styles/palettes/ repaint every color-bearing rule under
/// html[data-palette="<id>"], tokens.css carries the per-palette var
/// blocks, and assets/app/palette.js owns the attribute + broadcast live.
/// THIS file owns the server side: the manifest, the serve-time attribute
/// (override > published > default), the Coolors ingestion that derives a
/// pasted palette and generates its sheet, and deletion.
///
/// Derivation law (transplant — the ONE home of the color math; the
/// template indexer, design_palette_index.dart, consumes it): a pasted
/// Coolors link yields 5 hexes; the lightness rank assigns roles
/// (darkest=dark, 2nd=accent, 3rd=field, 4th=beige/cards, lightest=paper);
/// every base color slot is re-rendered relative to its family anchor —
/// dh additive, saturation RATIO capped [0.3, 1.3] (uncapped, saturated
/// paper anchors turn the ramp gold), dL additive. The slots are
/// pre-indexed in assets/styles/palettes/_template.json (regenerated by
/// `arxa design palette-index`) so no CSS parsing happens here.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:path/path.dart' as p;

import 'palette_contrast.dart';

import 'package:crypto/crypto.dart' show sha256;

import 'design_axes.dart' show axisValuePattern;
import 'palette_derive.dart' show anchorsForN, normHex;

// ── color math (1:1 with genpalettes.mjs) ───────────────────────────────

List<int> hexToRgb(String hex) {
  final h = hex.replaceFirst('#', '');
  return [
    int.parse(h.substring(0, 2), radix: 16),
    int.parse(h.substring(2, 4), radix: 16),
    int.parse(h.substring(4, 6), radix: 16),
  ];
}

String rgbToHex(num r, num g, num b) {
  int c(num v) => v.round().clamp(0, 255);
  return '#${c(r).toRadixString(16).padLeft(2, '0')}'
      '${c(g).toRadixString(16).padLeft(2, '0')}'
      '${c(b).toRadixString(16).padLeft(2, '0')}';
}

/// [h 0..360, s 0..100, l 0..100]
List<double> rgbToHsl(num r, num g, num b) {
  final rn = r / 255, gn = g / 255, bn = b / 255;
  final mx = math.max(rn, math.max(gn, bn));
  final mn = math.min(rn, math.min(gn, bn));
  final l = (mx + mn) / 2;
  var h = 0.0, s = 0.0;
  if (mx != mn) {
    final d = mx - mn;
    s = l > 0.5 ? d / (2 - mx - mn) : d / (mx + mn);
    if (mx == rn) {
      h = (gn - bn) / d + (gn < bn ? 6 : 0);
    } else if (mx == gn) {
      h = (bn - rn) / d + 2;
    } else {
      h = (rn - gn) / d + 4;
    }
    h *= 60;
  }
  return [h, s * 100, l * 100];
}

List<int> hslToRgb(num h, num s, num l) {
  final hn = ((h % 360) + 360) % 360;
  final sn = (s.clamp(0, 100)) / 100, ln = (l.clamp(0, 100)) / 100;
  final c = (1 - (2 * ln - 1).abs()) * sn;
  final x = c * (1 - (((hn / 60) % 2) - 1).abs());
  final m = ln - c / 2;
  var r = 0.0, g = 0.0, b = 0.0;
  if (hn < 60) {
    r = c; g = x;
  } else if (hn < 120) {
    r = x; g = c;
  } else if (hn < 180) {
    g = c; b = x;
  } else if (hn < 240) {
    g = x; b = c;
  } else if (hn < 300) {
    r = x; b = c;
  } else {
    r = c; b = x;
  }
  return [((r + m) * 255).round(), ((g + m) * 255).round(), ((b + m) * 255).round()];
}

/// The transplant: [base] rendered relative to its family anchor
/// [baseAnchor], replayed on the palette's anchor [paletteAnchor].
String transplant(String base, String baseAnchor, String paletteAnchor) {
  final bm = hexToRgb(base), ba = hexToRgb(baseAnchor), ga = hexToRgb(paletteAnchor);
  final hm = rgbToHsl(bm[0], bm[1], bm[2]);
  final ha = rgbToHsl(ba[0], ba[1], ba[2]);
  final hg = rgbToHsl(ga[0], ga[1], ga[2]);
  final dh = hm[0] - ha[0];
  var sr = ha[1] == 0 ? 1.0 : hm[1] / ha[1];
  sr = sr.clamp(0.3, 1.3);
  final dl = hm[2] - ha[2];
  final out = hslToRgb(hg[0] + dh, hg[1] * sr, hg[2] + dl);
  return rgbToHex(out[0], out[1], out[2]);
}

// ── the manifest ─────────────────────────────────────────────────────────

class PaletteEntry {
  const PaletteEntry({
    required this.id,
    required this.name,
    required this.swatch,
    required this.themeColor,
    this.seeded = false,
    this.source,
    this.sheet,
    this.auto = true,
  });

  /// The contrast law (grilled 2026-09-11): AUTO palettes render through
  /// the solver — their contracted pairs pass WCAG 2.2 AA by construction.
  /// A hand edit flips it to MANUAL: the author's hexes ship verbatim, the
  /// editor keeps showing the red pairs, the gate keeps failing them.
  final bool auto;

  final String id;
  final String name;
  final List<String> swatch; // 3..7 hexes (the variable-width law, Q5)
  final String themeColor;
  final bool seeded;
  final String? source;
  final String? sheet;

  Map<String, Object?> toJson() => {
        'id': id,
        'name': name,
        'swatch': swatch,
        'themeColor': themeColor,
        if (seeded) 'seeded': true,
        if (source != null) 'source': source,
        if (sheet != null) 'sheet': sheet,
        if (!auto) 'auto': false,
      };

  static PaletteEntry? fromJson(Object? json) {
    if (json is! Map) return null;
    final id = json['id'], name = json['name'], themeColor = json['themeColor'];
    final swatch = json['swatch'];
    if (id is! String || !axisValuePattern.hasMatch(id)) return null;
    if (name is! String || themeColor is! String) return null;
    if (swatch is! List || swatch.length < 3 || swatch.length > 7) {
      return null;
    }
    return PaletteEntry(
      id: id,
      name: name,
      swatch: [for (final s in swatch) s.toString()],
      themeColor: themeColor,
      seeded: json['seeded'] == true,
      source: json['source'] as String?,
      sheet: json['sheet'] as String?,
      auto: json['auto'] != false,
    );
  }
}

class PaletteManifest {
  PaletteManifest({required this.defaultId, required this.palettes});

  final String defaultId;
  final List<PaletteEntry> palettes;

  List<String> get ids => [for (final e in palettes) e.id];

  bool declares(String id) => palettes.any((e) => e.id == id);

  /// Null when the artifact declares no palette plane (or the manifest is
  /// malformed — a broken declaration disables the axis, never guesses).
  static PaletteManifest? load(String artifactDir) {
    try {
      final f = File(p.join(artifactDir, 'palettes.json'));
      if (!f.existsSync()) return null;
      final parsed = jsonDecode(f.readAsStringSync());
      if (parsed is! Map) return null;
      final def = parsed['default'];
      final list = parsed['palettes'];
      if (def is! String || list is! List) return null;
      final entries = <PaletteEntry>[];
      for (final raw in list) {
        final e = PaletteEntry.fromJson(raw);
        if (e == null) return null;
        entries.add(e);
      }
      if (entries.isEmpty || !entries.any((e) => e.id == def)) return null;
      return PaletteManifest(defaultId: def, palettes: entries);
    } catch (_) {
      return null;
    }
  }

  void save(String artifactDir) {
    final f = File(p.join(artifactDir, 'palettes.json'));
    const encoder = JsonEncoder.withIndent('  ');
    f.writeAsStringSync(encoder.convert({
      'version': 1,
      'comment':
          'Palette plane declaration (VERIFY ADDENDUM 17). id = html[data-palette] value; sheet = generated override under /assets/styles/palettes/ (the default palette is the base corpus, no sheet); swatch = the declared hexes (3..7 — the variable-width law; N=5 is the Coolors order); themeColor = meta theme-color while the palette is active. Pasted Coolors palettes are appended here by the dial server with a generated sheet, persist, and ship on the next eject.',
      'default': defaultId,
      'palettes': [for (final e in palettes) e.toJson()],
    }));
  }
}

/// The tokens file's one home, two layouts (plan amendment): site-layout
/// artifacts carry ui/styles/common/tokens.css; app-layout artifacts
/// (hello-hda) have no ui/styles tree and carry assets/css/tokens.css —
/// created on demand by ingest/update/the indexer's renderSeeded. Every
/// tokens.css touchpoint resolves HERE.
String tokensCssPath(String artifactDir) {
  final site = p.join(artifactDir, 'ui', 'styles', 'common', 'tokens.css');
  if (File(site).existsSync()) return site;
  return p.join(artifactDir, 'assets', 'css', 'tokens.css');
}

/// The deletion strip: remove one entry's appended var block (comment +
/// [data-palette="<id>"] { ... }) from tokens.css text.
String stripTokensBlock(String text, String id) {
  return text.replaceAll(
      RegExp(
          '\\n*/\\* pasted palette $id[^\\n]*\\*/\\n\\[data-palette="$id"\\] \\{[^}]*\\}\\n?'),
      '\n');
}

// ── the serve-time application ───────────────────────────────────────────

final _paletteAttrPattern = RegExp(r'\s+data-palette="[^"]*"');
final _htmlTagPattern = RegExp(r'<html\b[^>]*>');

class ServedPalette {
  const ServedPalette({
    required this.html,
    required this.active,
    required this.published,
    required this.palettesConfig,
  });

  /// The page with data-palette set on the <html> tag.
  final String html;

  /// What this page renders (?palette= override > published > default).
  final String active;

  /// What the store publishes (or the manifest default).
  final String published;

  /// The island's palettes array (manifest entries).
  final List<Map<String, Object?>> palettesConfig;
}

/// Resolve and apply the palette for one served page. Precedence mirrors
/// the axes law: a VALID ?palette= override beats the stored pick beats
/// the manifest default; unknown values fall through silently.
ServedPalette applyPaletteToServedHtml(
  String html, {
  required Map<String, String> query,
  required String? stored,
  required PaletteManifest manifest,
}) {
  String resolve(String? overrideValue, String? storedValue) {
    if (overrideValue != null && manifest.declares(overrideValue)) {
      return overrideValue;
    }
    if (storedValue != null && manifest.declares(storedValue)) {
      return storedValue;
    }
    return manifest.defaultId;
  }

  final published = resolve(null, stored);
  final active = resolve(query['palette'], stored);

  var out = html;
  final htmlMatch = _htmlTagPattern.firstMatch(out);
  if (htmlMatch != null) {
    final tag = htmlMatch.group(0)!;
    final stripped = tag.replaceAll(_paletteAttrPattern, '');
    final selfClosed = stripped.endsWith('/>');
    final core =
        stripped.substring(0, stripped.length - (selfClosed ? 2 : 1));
    final next = '$core data-palette="$active"${selfClosed ? '/>' : '>'}';
    if (next != tag) out = out.replaceFirst(tag, next);
  }

  // Wire every declared override sheet (ADDENDUM 18): the artifact's base
  // frame statically links the seeded sheets only — a pasted palette's
  // sheet existed on disk but was never <link>ed, so its tokens.css block
  // flipped while the 57 override rules stayed base (the "mixed palette
  // but nothing changes" report). Dedup by href keeps statically linked
  // sheets single; injected last so the cascade matches the static links.
  final links = StringBuffer();
  for (final e in manifest.palettes) {
    final sheet = e.sheet;
    if (sheet == null || sheet.isEmpty) continue;
    if (out.contains('href="$sheet"')) continue;
    links.write(
        '<link rel="stylesheet" href="$sheet" data-palette-sheet="${e.id}">');
  }
  if (links.isNotEmpty) {
    out = out.replaceFirst('</head>', '$links</head>');
  }

  // theme-color follows the ACTIVE palette at serve time (palette.js
  // keeps it current on live switches — this kills the wrong-chrome
  // flash before first paint).
  for (final e in manifest.palettes) {
    if (e.id != active) continue;
    out = out.replaceFirstMapped(
        RegExp(r'(<meta[^>]*name="theme-color"[^>]*content=")[^"]*(")'),
        (m) => '${m[1]}${e.themeColor}${m[2]}');
    break;
  }

  return ServedPalette(
    html: out,
    active: active,
    published: published,
    palettesConfig: [for (final e in manifest.palettes) e.toJson()],
  );
}

// ── Coolors ingestion ────────────────────────────────────────────────────

final _coolorsPattern = RegExp(
    r'(?:coolors\.co)?/?(?:palette/)?([0-9a-fA-F]{6}(?:-[0-9a-fA-F]{6}){4})');

/// Parse a Coolors link (or bare slug) into its 5 hexes, lowercased.
/// There is no official Coolors API (every /api/* candidate 404s; the
/// pages are CSR) — the URL slug IS the palette.
List<String>? parseCoolorsSlug(String input) {
  final match = _coolorsPattern.firstMatch(input.trim());
  if (match == null) return null;
  final slug = match.group(1)!;
  if (slug.split('-').length != 5) return null;
  return [for (final h in slug.split('-')) h.toLowerCase()];
}

/// The lightness-rank role law: sorted by HSL lightness, the five hexes
/// map darkest->dark, 2nd->accent, 3rd->field, 4th->beige (cards),
/// lightest->paper. Verified against Marine Blue and Green Oasis.
Map<String, String> anchorsFor(List<String> hexes) {
  double lightness(String h) {
    final rgb = hexToRgb(h);
    return rgbToHsl(rgb[0], rgb[1], rgb[2])[2];
  }
  final sorted = [...hexes]..sort((a, b) => lightness(a).compareTo(lightness(b)));
  return {
    'dark': sorted[0],
    'accent': sorted[1],
    'field': sorted[2],
    'beige': sorted[3],
    'paper': sorted[4],
  };
}

/// The pre-indexed color slots (generated by genpalettes.mjs — the design
/// ships it at assets/styles/palettes/_template.json).
/// A family-level pair (the general contract): every solid TEXT rule of
/// [fg] family must pass [level] against every surface RULE and every
/// mapped surface TOKEN of the [on] families. Expanded at solve time —
/// the artifact's real co-locations, erring readable.
class FamilyPair {
  const FamilyPair({required this.fg, required this.on, required this.level});
  final String fg;
  final List<String> on;
  final String level;
}

class PaletteTemplate {
  PaletteTemplate(
      {required this.anchors,
      required this.tokens,
      required this.rules,
      this.pairs = const [],
      this.familyPairs = const [],
      this.surfaces = const {},
      this.declaresContract = false});

  /// Base palette family anchors: family -> base hex.
  final Map<String, String> anchors;
  final List<Map<String, Object?>> tokens;
  final List<Map<String, Object?>> rules;

  /// The contrast contract (grilled 2026-09-11): explicit token/rule
  /// pairs, the family-level general pairs, and the family -> surface
  /// token map. [declaresContract] distinguishes a MODERN template
  /// (the keys are present, even if vacuously empty) from a legacy one
  /// (no keys at all): the solver no-ops on empty, and only a legacy
  /// template earns the gate's author-the-contract advisory.
  final List<ContrastPair> pairs;
  final List<FamilyPair> familyPairs;
  final Map<String, String> surfaces;
  final bool declaresContract;

  static PaletteTemplate? load(String artifactDir) {
    try {
      final f = File(p.join(
          artifactDir, 'assets', 'styles', 'palettes', '_template.json'));
      if (!f.existsSync()) return null;
      final parsed = jsonDecode(f.readAsStringSync());
      if (parsed is! Map) return null;
      final anchors = <String, String>{};
      (parsed['anchors'] as Map).forEach((k, v) => anchors['$k'] = '$v');
      final surfaces = <String, String>{};
      final rawSurfaces = parsed['surfaces'];
      if (rawSurfaces is Map) {
        rawSurfaces.forEach((k, v) => surfaces['$k'] = '$v');
      }
      final rawFamily = parsed['familyPairs'];
      final familyPairs = <FamilyPair>[];
      if (rawFamily is List) {
        for (final fp in rawFamily) {
          if (fp is! Map) continue;
          final fg = fp['fg'], on = fp['on'], level = fp['level'];
          if (fg is! String || on is! List || level is! String) continue;
          familyPairs.add(FamilyPair(
              fg: fg,
              on: [for (final f in on) '$f'],
              level: level));
        }
      }
      return PaletteTemplate(
        anchors: anchors,
        tokens: [
          for (final t in parsed['tokens'] as List)
            Map<String, Object?>.from(t as Map)
        ],
        rules: [
          for (final r in parsed['rules'] as List)
            Map<String, Object?>.from(r as Map)
        ],
        pairs: contractFromTemplate(parsed),
        familyPairs: familyPairs,
        surfaces: surfaces,
        declaresContract: parsed.containsKey('pairs') ||
            parsed.containsKey('familyPairs') ||
            parsed.containsKey('surfaces'),
      );
    } catch (_) {
      return null;
    }
  }
}

/// The update conflict (Q4): the edited swatch set already belongs to
/// another palette. An ArgumentError so the route's existing catch shapes
/// it — and a named type so the route can answer 409 + conflictsWith.
class PaletteConflictError extends ArgumentError {
  PaletteConflictError(this.conflictsWith)
      : super('swatch set already belongs to palette "$conflictsWith"');

  /// The palette id holding the identical swatch set.
  final String conflictsWith;
}

/// Ingestion + deletion. The manifest saves LAST, so a crash mid-ingest
/// leaves an orphan sheet file, never a manifest pointing at nothing.
class PaletteIngestion {
  PaletteIngestion({required this.artifactDir});

  final String artifactDir;

  String _derive(Map<String, Object?> slot, Map<String, String> anchors,
      PaletteTemplate template,
      [Map<String, String>? solved, String? key]) {
    // The contrast engine's answer first: a solved slot ships the solved
    // hex (hex form) or the solved rgb (triplet forms) — same shape, new
    // lightness. Unsolved/absent falls through to the transplant.
    final solvedHex = key == null ? null : solved?[key];
    if (solvedHex != null) {
      final form = slot['form'] as String;
      if (form == 'hex') return solvedHex;
      final rgb = hexToRgb(solvedHex);
      return '${rgb[0]}, ${rgb[1]}, ${rgb[2]}';
    }
    final family = slot['family'] as String;
    final baseAnchor = template.anchors[family]!;
    final paletteAnchor = anchors[family]!;
    final form = slot['form'] as String;
    if (form == 'hex') {
      return transplant(slot['base'] as String, baseAnchor, paletteAnchor);
    }
    final base = slot['base'] as List;
    final baseHex = rgbToHex(base[0] as num, base[1] as num, base[2] as num);
    final derived = transplant(baseHex, baseAnchor, paletteAnchor);
    final rgb = hexToRgb(derived);
    return '${rgb[0]}, ${rgb[1]}, ${rgb[2]}';
  }

  // ── the contrast engine seam (grilled 2026-09-11) ──────────────────
  // The slot map every solve renders from: token name -> derived core
  // hex, plus every rule slot under its implicit key 'r<i>s<j>' (and a
  // template 'key' aliasing the rule's first slot). The pasted anchors
  // never enter this map — they are inviolate by construction; every
  // value here is a transplant output the solver may move.
  Map<String, String> _slotHexes(
      Map<String, String> anchors, PaletteTemplate template) {
    final map = <String, String>{};
    for (final token in template.tokens) {
      map[token['name'] as String] =
          _slotCoreHex(token, anchors, template);
    }
    for (var i = 0; i < template.rules.length; i++) {
      final slots = (template.rules[i]['slots'] as List).cast<Map>();
      for (var j = 0; j < slots.length; j++) {
        map['r${i}s$j'] = _slotCoreHex(
            Map<String, Object?>.from(slots[j]), anchors, template);
      }
      final key = template.rules[i]['key'];
      if (key is String && slots.isNotEmpty) {
        map[key] = map['r${i}s0']!;
      }
    }
    return map;
  }

  String _slotCoreHex(Map<String, Object?> slot,
      Map<String, String> anchors, PaletteTemplate template) {
    final family = slot['family'] as String;
    final baseAnchor = template.anchors[family]!;
    final paletteAnchor = anchors[family]!;
    final base = slot['base'];
    if (base is String) return transplant(base, baseAnchor, paletteAnchor);
    final b = base as List;
    return transplant(
        rgbToHex(b[0] as num, b[1] as num, b[2] as num),
        baseAnchor,
        paletteAnchor);
  }

  /// The alias -> implicit-key map ('preloader-text' -> 'r4s0'): the
  /// contract may speak readable keys, but ONE key space — implicit —
  /// feeds the solver, the flip candidates, and the renderer, so a move
  /// can never land on an alias the renderer doesn't read.
  Map<String, String> _aliasMap(PaletteTemplate template) => {
        for (var i = 0; i < template.rules.length; i++)
          if (template.rules[i]['key'] is String)
            template.rules[i]['key'] as String: 'r${i}s0',
      };

  /// Expand the template's contract into concrete pairs: the explicit
  /// list (aliases canonicalized to implicit keys) plus familyPairs
  /// crossed over solid text rules (color:) × surface rules (background:)
  /// and mapped surface tokens. rgba-form text slots are the decorative
  /// ghosts — they never enter familyPairs.
  List<ContrastPair> _expandedPairs(PaletteTemplate template) {
    final aliases = _aliasMap(template);
    String canon(String k) => aliases[k] ?? k;
    final pairs = [
      for (final p0 in template.pairs)
        ContrastPair(
            fg: canon(p0.fg), bg: canon(p0.bg), level: p0.level,
            fgAlpha: p0.fgAlpha)
    ];
    if (template.familyPairs.isEmpty) return pairs;
    for (var i = 0; i < template.rules.length; i++) {
      final rule = template.rules[i];
      final tpl = (rule['tpl'] as String).trimLeft();
      final slots = (rule['slots'] as List);
      if (slots.isEmpty || !tpl.startsWith('color:')) continue;
      final first = Map<String, Object?>.from(slots.first as Map);
      if (first['form'] != 'hex') continue; // ghost — exempt
      final fgFam = first['family'] as String;
      for (final fp in template.familyPairs) {
        if (fp.fg != fgFam) continue;
        for (var k = 0; k < template.rules.length; k++) {
          final srule = template.rules[k];
          final stpl = (srule['tpl'] as String).trimLeft();
          if (!stpl.startsWith('background')) continue;
          final ss = (srule['slots'] as List);
          if (ss.isEmpty) continue;
          final sslot = Map<String, Object?>.from(ss.first as Map);
          if (sslot['form'] != 'hex') continue;
          if (!fp.on.contains(sslot['family'])) continue;
          pairs.add(ContrastPair(fg: 'r${i}s0', bg: 'r${k}s0', level: fp.level));
        }
        for (final fam in fp.on) {
          final token = template.surfaces[fam];
          if (token != null && template.tokens.any((t) => t['name'] == token)) {
            pairs.add(ContrastPair(fg: 'r${i}s0', bg: token, level: fp.level));
          }
        }
      }
    }
    return pairs;
  }

  /// Solve the slot map against the contract (solve:false = MANUAL: the
  /// raw transplant map ships, the editor/gate own the visibility). The
  /// flip candidates: rule text slots and non-surface ink tokens may
  /// INVERT POLARITY (dark-family derivation <-> paper-family) — the
  /// palette's surfaces are its character; a mid-dark surface gets light
  /// text, never a bleach.
  ({Map<String, String> hexes, List<SolveMove> moves, List<String> unsolved})
      _solvedSlots(Map<String, String> anchors, PaletteTemplate template,
          {required bool solve}) {
    final raw = _slotHexes(anchors, template);
    if (!solve || template.pairs.isEmpty && template.familyPairs.isEmpty) {
      return (hexes: raw, moves: const [], unsolved: const []);
    }
    final surfaceTokens = template.surfaces.values.toSet();
    String? flipCandidate(String slot) {
      final isRule = slot.startsWith('r');
      final isToken = template.tokens.any((t) => t['name'] == slot);
      if (!isRule && !(isToken && !surfaceTokens.contains(slot))) return null;
      Map<String, Object?>? slotDef;
      if (isRule) {
        final m = RegExp(r'r(\d+)s(\d+)$').firstMatch(slot);
        if (m == null) return null;
        final rule = template.rules[int.parse(m.group(1)!)];
        final slots = (rule['slots'] as List);
        final j = int.parse(m.group(2)!);
        if (j >= slots.length) return null;
        slotDef = Map<String, Object?>.from(slots[j] as Map);
      } else {
        slotDef = Map<String, Object?>.from(
            template.tokens.firstWhere((t) => t['name'] == slot));
      }
      final family = slotDef['family'] as String;
      final opposite = family == 'dark' ? 'paper' : 'dark';
      final target = anchors[opposite];
      if (target == null) return null;
      final baseAnchor = template.anchors[family];
      if (baseAnchor == null) return null;
      final base = slotDef['base'];
      if (base is String) return transplant(base, baseAnchor, target);
      final b = base as List;
      return transplant(
          rgbToHex(b[0] as num, b[1] as num, b[2] as num),
          baseAnchor,
          target);
    }

    final (hexes, moves, unsolved) = solveContrast(
        slotHexes: raw,
        pairs: _expandedPairs(template),
        alt: flipCandidate);
    return (hexes: hexes, moves: moves, unsolved: unsolved);
  }

  String _tokenValue(Map<String, Object?> token, Map<String, String> anchors,
      PaletteTemplate template,
      [Map<String, String>? solved]) {
    final family = token['family'] as String;
    final baseAnchor = template.anchors[family]!;
    final paletteAnchor = anchors[family]!;
    final form = token['form'] as String;
    // The contrast engine's solved hex rides first — the alpha and shadow
    // forms re-derive their rgb from it, keeping the soft/ghost depth.
    final solvedHex = solved?[token['name'] as String];
    String derivedHex() {
      if (solvedHex != null) return solvedHex;
      final base = token['base'];
      if (base is String) return transplant(base, baseAnchor, paletteAnchor);
      final b = base as List;
      return transplant(rgbToHex(b[0] as num, b[1] as num, b[2] as num),
          baseAnchor, paletteAnchor);
    }

    if (form == 'hex') return derivedHex();
    if (form.startsWith('rgba:')) {
      final rgb = hexToRgb(derivedHex());
      return 'rgba(${rgb[0]}, ${rgb[1]}, ${rgb[2]}, ${form.substring(5)})';
    }
    if (form.startsWith('shadow:')) {
      final rgb = hexToRgb(derivedHex());
      return form
          .substring(7)
          .replaceAll('{t}', '${rgb[0]}, ${rgb[1]}, ${rgb[2]}');
    }
    throw StateError('unknown token form: $form');
  }

  /// Paste-a-Coolors-link (grilled Q5/Q6): derive, generate the override
  /// sheet, append the tokens.css var block, extend the manifest. A repeat
  /// paste of the same five hexes returns the existing entry — no dupes.
  PaletteEntry ingest(String url) {
    final manifest = PaletteManifest.load(artifactDir);
    if (manifest == null) {
      throw StateError('this artifact declares no palette plane');
    }
    final template = PaletteTemplate.load(artifactDir);
    if (template == null) {
      throw StateError('palette template missing — regenerate the design');
    }
    final parsed = parseCoolorsSlug(url);
    if (parsed == null) {
      throw ArgumentError('not a Coolors link — expected coolors.co/<5 hexes>');
    }
    // Slug hexes arrive bare ('10002b'); the whole plane speaks '#'-prefixed
    // (ids strip it with substring(1), themeColor keeps it, swatches match
    // the seeded entries' shape).
    final hexes = [for (final h in parsed) '#$h'];
    final wanted = ([...hexes]..sort()).join('-');
    final anchors = anchorsFor(hexes);
    for (final e in manifest.palettes) {
      final have =
          ([...e.swatch.map((s) => s.toLowerCase())]..sort()).join('-');
      if (have == wanted) {
        // Dedup — but a crash or manual cleanup between the artifact
        // writes can leave the entry pointing at a missing sheet or a
        // stripped tokens block (the c-2e1f27 half-wipe, ADDENDUM 18).
        // Repair in place instead of returning a hollow card.
        if (!_artifactsIntact(e)) renderArtifacts(e, anchors, template);
        return e;
      }
    }
    var id = 'c-${anchors['dark']!.substring(1)}';
    var n = 2;
    while (manifest.declares(id)) {
      id = 'c-${anchors['dark']!.substring(1)}-$n';
      n++;
    }

    final entry = PaletteEntry(
      id: id,
      name: 'Coolors ${anchors['dark']!.substring(1).toUpperCase()}',
      swatch: hexes,
      themeColor: anchors['accent']!,
      source: url,
      sheet: '/assets/styles/palettes/palette-$id.css',
    );
    renderArtifacts(entry, anchors, template);
    manifest.palettes.add(entry);
    manifest.save(artifactDir);
    _sweepCustomSlot(entry.id);
    return entry;
  }

  /// The one-custom-slot law (operator, 2026-09-02): the plane carries the
  /// seeded picks plus exactly ONE custom slot — a genuinely new entry
  /// REPLACES the previous custom, stripping its sheet and tokens block
  /// through the same deletion path the dial's × uses. Dedup hits return
  /// early and never reach this sweep.
  void _sweepCustomSlot(String keepId) {
    final stale = PaletteManifest.load(artifactDir)!
        .palettes
        .where((e) => !e.seeded && e.id != keepId)
        .map((e) => e.id)
        .toList();
    for (final id in stale) {
      delete(id);
    }
  }

  /// True when the entry's sheet file and tokens.css block both exist.
  bool _artifactsIntact(PaletteEntry e) {
    final sheet = e.sheet;
    if (sheet != null) {
      if (!File(p.join(artifactDir, sheet.replaceFirst('/', '')))
          .existsSync()) {
        return false;
      }
    }
    final tokensFile = File(tokensCssPath(artifactDir));
    if (!tokensFile.existsSync()) return false;
    return tokensFile
        .readAsStringSync()
        .contains('[data-palette="${e.id}"]');
  }

  /// Write (or rewrite) the entry's two artifacts: the generated override
  /// sheet and the appended tokens.css var block (the ingest/birth path).
  void renderArtifacts(PaletteEntry entry, Map<String, String> anchors,
      PaletteTemplate template,
      {bool solve = true}) {
    renderSheet(entry, anchors, template, solve: solve);
    final tokensFile = File(tokensCssPath(artifactDir));
    tokensFile.parent.createSync(recursive: true);
    tokensFile.writeAsStringSync(
        _tokensBlock(entry, anchors, template, solve: solve),
        mode: FileMode.append);
  }

  /// The override sheet, written atomically (temp file + rename): update
  /// rewrites a sheet the manifest ALREADY points at, and a crash
  /// mid-write must never leave a truncated one referenced (the crash
  /// law). The path derives from the id — sheet fields name it by
  /// construction.
  void renderSheet(PaletteEntry entry, Map<String, String> anchors,
      PaletteTemplate template,
      {bool solve = true}) {
    final id = entry.id;
    final hexes = entry.swatch;
    final solved = _solvedSlots(anchors, template, solve: solve);
    // the override sheet — the solve log rides INSIDE the header comment
    // (leaked log lines would be invalid CSS and pollute the P5 reader).
    final buf = StringBuffer()
      ..writeln(
          '/* palette-$id.css — GENERATED override sheet (VERIFY ADDENDUM 17,')
      ..writeln(
          '   pasted Coolors ${hexes.join('-')}). Derived by the transplant law;')
      ..writeln(
          '   see assets/styles/palettes/_template.json.');
    if (solved.moves.isNotEmpty) {
      buf
        ..writeln('   contrast: WCAG 2.2 AA solved at render — '
            '${solved.moves.length} move(s):')
        ..writeAll([for (final m in solved.moves) '     $m\n']);
    }
    if (solved.unsolved.isNotEmpty) {
      buf.writeln(
          '   contrast: UNSOLVED after solve (extreme ramp): '
          '${solved.unsolved.join('; ')}');
    }
    buf
      ..writeln('   Do not hand-edit. */')
      ..writeln();
    for (final rule in template.rules) {
      final at = [for (final a in rule['at'] as List) '$a'];
      final sel = (rule['sel'] as String).replaceAll('{id}', id);
      var tpl = rule['tpl'] as String;
      final slots = rule['slots'] as List;
      final ri = template.rules.indexOf(rule);
      for (var i = 0; i < slots.length; i++) {
        tpl = tpl.replaceAll('{$i}',
            _derive(Map<String, Object?>.from(slots[i] as Map), anchors,
                template, solved.hexes, 'r${ri}s$i'));
      }
      final ind = '  ' * at.length;
      for (var k = 0; k < at.length; k++) {
        buf.writeln('${'  ' * k}${at[k]} {');
      }
      buf
        ..writeln('$ind$sel {')
        ..writeln('$ind  $tpl')
        ..writeln('$ind}');
      for (var k = at.length - 1; k >= 0; k--) {
        buf.writeln('${'  ' * k}}');
      }
      buf.writeln();
    }
    final sheet = File(p.join(
        artifactDir, 'assets', 'styles', 'palettes', 'palette-$id.css'));
    sheet.parent.createSync(recursive: true);
    final tmp = File('${sheet.path}.tmp');
    tmp.writeAsStringSync(buf.toString());
    tmp.renameSync(sheet.path);
  }

  /// One entry's tokens.css var block text (appended on birth; deletion
  /// and update strip by id).
  String _tokensBlock(PaletteEntry entry, Map<String, String> anchors,
      PaletteTemplate template,
      {bool solve = true}) {
    final id = entry.id;
    final hexes = entry.swatch;
    final solved = _solvedSlots(anchors, template, solve: solve);
    final tokens = StringBuffer()
      ..writeln()
      ..writeln(
          '/* pasted palette $id (${hexes.join('-')}) — ingestion, do not hand-edit */')
      ..writeln('[data-palette="$id"] {');
    for (final token in template.tokens) {
      tokens.writeln(
          '  ${token['name']}: ${_tokenValue(token, anchors, template, solved.hexes)};');
    }
    tokens.writeln('}');
    return tokens.toString();
  }

  /// Strip + append in ONE write (the update law): the old block goes and
  /// the re-derived block lands together — there is no crash window
  /// between two writes because there is only one.
  void replaceTokensBlock(PaletteEntry entry, Map<String, String> anchors,
      PaletteTemplate template,
      {bool solve = true}) {
    final tokensFile = File(tokensCssPath(artifactDir));
    final current =
        tokensFile.existsSync() ? tokensFile.readAsStringSync() : '';
    tokensFile.parent.createSync(recursive: true);
    tokensFile.writeAsStringSync(
        stripTokensBlock(current, entry.id) +
            _tokensBlock(entry, anchors, template, solve: solve));
  }

  /// Deletion is a dial action (grilled Q13): non-seeded entries only —
  /// the shipped palettes stay. The default can never be deleted. Returns
  /// the remaining entries.
  List<PaletteEntry> delete(String id) {
    final manifest = PaletteManifest.load(artifactDir);
    if (manifest == null) {
      throw StateError('this artifact declares no palette plane');
    }
    final entry = manifest.palettes.where((e) => e.id == id).firstOrNull;
    if (entry == null) throw ArgumentError('no such palette: $id');
    if (entry.seeded || id == manifest.defaultId) {
      throw ArgumentError('the shipped palettes stay — only pasted ones go');
    }
    manifest.palettes.removeWhere((e) => e.id == id);
    if (entry.sheet != null) {
      final f = File(p.join(artifactDir, entry.sheet!.replaceFirst('/', '')));
      if (f.existsSync()) f.deleteSync();
    }
    final tokensFile = File(tokensCssPath(artifactDir));
    if (tokensFile.existsSync()) {
      tokensFile.writeAsStringSync(
          stripTokensBlock(tokensFile.readAsStringSync(), id));
    }
    manifest.save(artifactDir);
    return manifest.palettes;
  }

  /// In-dial editing (grilled Q4): 3..7 hexes, each a valid 6-digit hex —
  /// the engine accepts 1..7 but the manifest floors at 3 (the dial law).
  /// Editing the DEFAULT palette FORKS into the one custom slot (the base
  /// corpus stays hand-owned); any other palette edits IN PLACE — stable
  /// id, so published picks and ?palette= links never break. A swatch set
  /// identical to another palette's refuses, naming the conflict
  /// (PaletteConflictError). Artifacts land before the manifest saves
  /// (the crash law, unchanged).
  ({PaletteEntry entry, bool forked, List<PaletteEntry> palettes}) update(
      String id, List<String> hexes,
      {String? name, bool? auto}) {
    final manifest = PaletteManifest.load(artifactDir);
    if (manifest == null) {
      throw StateError('this artifact declares no palette plane');
    }
    final template = PaletteTemplate.load(artifactDir);
    if (template == null) {
      throw StateError('palette template missing — regenerate the design');
    }
    if (hexes.length < 3 || hexes.length > 7) {
      throw ArgumentError('3..7 hexes, got ${hexes.length}');
    }
    final normalized = <String>[];
    for (final h in hexes) {
      try {
        normalized.add(normHex(h));
      } on FormatException catch (e) {
        throw ArgumentError(e.message);
      }
    }
    // The sorted-lowercase swatch-set compare, one law with ingest.
    String keyOf(List<String> swatch) =>
        ([...swatch.map((s) => s.toLowerCase())]..sort()).join('-');
    final wanted = keyOf(normalized);
    final anchors = anchorsForN(normalized);
    if (id == manifest.defaultId) {
      // FORK (Q4): dedup against ALL entries — a fork duplicating any
      // palette (the default included) refuses, naming the conflict.
      for (final e in manifest.palettes) {
        if (keyOf(e.swatch) == wanted) throw PaletteConflictError(e.id);
      }
      var forkId = 'c-${anchors['dark']!.substring(1)}';
      var n = 2;
      while (manifest.declares(forkId)) {
        forkId = 'c-${anchors['dark']!.substring(1)}-$n';
        n++;
      }
      final entry = PaletteEntry(
        id: forkId,
        name: name ?? 'Custom ${anchors['dark']!.substring(1).toUpperCase()}',
        swatch: normalized,
        themeColor: anchors['accent']!,
        source: 'dial-edit:fork-of-$id',
        sheet: '/assets/styles/palettes/palette-$forkId.css',
        auto: auto ?? true,
      );
      renderArtifacts(entry, anchors, template, solve: entry.auto);
      manifest.palettes.add(entry);
      manifest.save(artifactDir);
      _sweepCustomSlot(entry.id);
      return (
        entry: entry,
        forked: true,
        palettes: PaletteManifest.load(artifactDir)!.palettes,
      );
    }
    // IN PLACE (Q4): dedup against the OTHER entries; id/seeded/source/
    // sheet untouched; swatch/themeColor (and name when given) re-derived.
    final index = manifest.palettes.indexWhere((e) => e.id == id);
    if (index < 0) throw ArgumentError('no such palette: $id');
    final old = manifest.palettes[index];
    for (final e in manifest.palettes) {
      if (e.id != id && keyOf(e.swatch) == wanted) {
        throw PaletteConflictError(e.id);
      }
    }
    if (old.sheet == null) {
      throw StateError(
          'palette $id declares no sheet — run arxa design palette-index');
    }
    final entry = PaletteEntry(
      id: old.id,
      name: name ?? old.name,
      swatch: normalized,
      themeColor: anchors['accent']!,
      seeded: old.seeded,
      source: old.source,
      sheet: old.sheet,
      auto: auto ?? old.auto,
    );
    renderSheet(entry, anchors, template, solve: entry.auto);
    replaceTokensBlock(entry, anchors, template, solve: entry.auto);
    manifest.palettes[index] = entry;
    manifest.save(artifactDir);
    return (entry: entry, forked: false, palettes: manifest.palettes);
  }

  /// Re-solve (the editor's Re-solve button, grilled Q5): re-render the
  /// palette through the contrast engine with solving ON and mark it
  /// AUTO again. The author's live voice — same id, same swatch, the
  /// contracted pairs pass once more.
  ({PaletteEntry entry, List<PaletteEntry> palettes, List<String> unsolved})
      resolve(String id) {
    final manifest = PaletteManifest.load(artifactDir);
    if (manifest == null) {
      throw StateError('this artifact declares no palette plane');
    }
    final template = PaletteTemplate.load(artifactDir);
    if (template == null) {
      throw StateError('palette template missing — regenerate the design');
    }
    final index = manifest.palettes.indexWhere((e) => e.id == id);
    if (index < 0) throw ArgumentError('no such palette: $id');
    final old = manifest.palettes[index];
    if (old.sheet == null) {
      throw StateError(
          'palette $id declares no sheet — run arxa design palette-index');
    }
    final anchors = anchorsForN(old.swatch);
    final entry = PaletteEntry(
      id: old.id,
      name: old.name,
      swatch: old.swatch,
      themeColor: anchors['accent'] ?? old.themeColor,
      seeded: old.seeded,
      source: old.source,
      sheet: old.sheet,
      auto: true,
    );
    final solved = _solvedSlots(anchors, template, solve: true);
    renderSheet(entry, anchors, template, solve: true);
    replaceTokensBlock(entry, anchors, template, solve: true);
    manifest.palettes[index] = entry;
    manifest.save(artifactDir);
    return (
      entry: entry,
      palettes: manifest.palettes,
      unsolved: solved.unsolved,
    );
  }
}

// ── the deployed-dial bake ───────────────────────────────────────────────

/// Resolve everything the ejected worker needs for the static palette/dial
/// channel (grilled Q7-Q10): the manifest object, the publishable-key
/// channel (the SERVICE key never ships), the design's registered id, the
/// published palette, and the author token's SHA-256. Null when the
/// artifact declares no palettes; a manifest-only bake when the Supabase
/// channel is under-configured (the deployed site still stamps
/// data-palette and serves /palettes.json — no dial, no live publish).
class DeployedDialBake {
  DeployedDialBake._(this._url, this._serviceKey);

  final String _url;
  final String _serviceKey;

  // The dial's network discipline (arxa_dial.dart, 2026-08-25): timeouts
  // convert a stall into a fast failure, never a held socket.
  final HttpClient _http = HttpClient()
    ..connectionTimeout = const Duration(seconds: 5)
    ..idleTimeout = const Duration(seconds: 30);

  Future<(int, String)> _req(String method, String path,
      {Object? body, Map<String, String>? headers}) async {
    final request = await _http
        .openUrl(method, Uri.parse('$_url/rest/v1/$path'))
        .timeout(const Duration(seconds: 8));
    request.headers.set('apikey', _serviceKey);
    request.headers.set('Authorization', 'Bearer $_serviceKey');
    headers?.forEach(request.headers.set);
    if (body != null) {
      request.headers.contentType = ContentType.json;
      request.write(jsonEncode(body));
    }
    final res = await request.close().timeout(const Duration(seconds: 10));
    return (res.statusCode, await utf8.decoder.bind(res).join());
  }

  Future<String> _designId(String project, String artifact) async {
    final get = await _req('GET',
        'arxa_dial_designs?project=eq.${Uri.encodeComponent(project)}&artifact=eq.${Uri.encodeComponent(artifact)}&select=id');
    if (get.$1 < 300) {
      final rows = jsonDecode(get.$2);
      if (rows is List && rows.isNotEmpty && rows.first is Map) {
        final id = (rows.first as Map)['id'];
        if (id is String) return id;
      }
    }
    final post = await _req('POST', 'arxa_dial_designs',
        body: {'project': project, 'artifact': artifact},
        headers: {'Prefer': 'return=representation'});
    if (post.$1 < 300) {
      final rows = jsonDecode(post.$2);
      if (rows is List && rows.isNotEmpty && rows.first is Map) {
        final id = (rows.first as Map)['id'];
        if (id is String) return id;
      }
    }
    // The 409 race (two first-ejects at once): the row provably exists —
    // read it back.
    return _designId(project, artifact);
  }

  static Future<Map<String, Object?>?> resolve({
    required String artifactDir,
    required String project,
    required String artifact,
    Map<String, String>? env,
    String? credentialsFileText,
  }) async {
    final manifest = PaletteManifest.load(artifactDir);
    if (manifest == null) return null;
    final environment = env ?? Platform.environment;
    String? url = environment['ARXA_SUPABASE_URL'];
    String? serviceKey = environment['ARXA_SUPABASE_SERVICE_KEY'];
    String? publishableKey = environment['ARXA_SUPABASE_PUBLISHABLE_KEY'];
    if (credentialsFileText != null) {
      for (final line in credentialsFileText.split('\n')) {
        final m = RegExp(r'^(url|service_key|publishable_key)=(.+)$')
            .firstMatch(line.trim());
        if (m == null) continue;
        if (m.group(1) == 'url') url ??= m.group(2)!.trim();
        if (m.group(1) == 'service_key') serviceKey ??= m.group(2)!.trim();
        if (m.group(1) == 'publishable_key') {
          publishableKey ??= m.group(2)!.trim();
        }
      }
    }
    final manifestJson = <String, Object?>{
      'version': 1,
      'default': manifest.defaultId,
      'palettes': [for (final e in manifest.palettes) e.toJson()],
    };
    if (url == null ||
        url.isEmpty ||
        serviceKey == null ||
        serviceKey.isEmpty ||
        publishableKey == null ||
        publishableKey.isEmpty) {
      stderr.writeln('[eject] palette plane: manifest baked, dial channel '
          'off (ARXA_SUPABASE_URL + ARXA_SUPABASE_SERVICE_KEY + '
          'ARXA_SUPABASE_PUBLISHABLE_KEY required) — the deployed site '
          'stamps data-palette but ships no dial and no live publish.');
      return {'manifest': manifestJson, 'static': null, 'mintedAuthorToken': null};
    }
    final bake = DeployedDialBake._(url, serviceKey);
    final designId = await bake._designId(project, artifact);
    var published = manifest.defaultId;
    Map<String, String>? fontCell;
    final axes = await bake._req('GET',
        'arxa_dial_axes?design_id=eq.$designId&select=palette,font');
    if (axes.$1 < 300) {
      final rows = jsonDecode(axes.$2);
      if (rows is List && rows.isNotEmpty && rows.first is Map) {
        final pickCell = (rows.first as Map)['palette'];
        if (pickCell is String && manifest.declares(pickCell)) {
          published = pickCell;
        }
        // The font plane (grilled 2026-09-13): bake the published per-role
        // picks; the worker re-validates each against the baked manifest
        // (an id ahead of this deploy falls to the default, ADDENDUM 18's
        // font twin).
        final f = (rows.first as Map)['font'];
        if (f is Map) {
          fontCell = {
            for (final e in f.entries)
              if (e.key is String && e.value is String)
                e.key as String: e.value as String,
          };
        }
      }
    }
    // The author token: env wins, the stored hash carries across ejects,
    // and a first eject mints + prints ONCE.
    String? authorTokenToPrint;
    String? existingHash;
    final row = await bake._req('GET',
        'arxa_dial_designs?id=eq.$designId&select=author_token_hash');
    if (row.$1 < 300) {
      final rows = jsonDecode(row.$2);
      if (rows is List && rows.isNotEmpty && rows.first is Map) {
        existingHash = (rows.first as Map)['author_token_hash'] as String?;
      }
    }
    final envToken = environment['ARXA_DIAL_AUTHOR_TOKEN'];
    final String authorSha;
    if (envToken != null && envToken.isNotEmpty) {
      authorSha = sha256.convert(ascii.encode(envToken)).toString();
    } else if (existingHash != null && existingHash.isNotEmpty) {
      authorSha = existingHash;
    } else {
      final token = base64Url
          .encode(List<int>.generate(
              24, (_) => math.Random.secure().nextInt(256)))
          .replaceAll('=', '');
      authorSha = sha256.convert(ascii.encode(token)).toString();
      authorTokenToPrint = token;
    }
    if (authorSha != existingHash) {
      await bake._req('PATCH', 'arxa_dial_designs?id=eq.$designId',
          body: {'author_token_hash': authorSha});
    }
    return {
      'manifest': manifestJson,
      'static': {
        'artifact': artifact,
        'url': url,
        'anonKey': publishableKey,
        'designId': designId,
        'published': published,
        if (fontCell != null) 'font': fontCell,
        'authorSha256': authorSha,
      },
      'mintedAuthorToken': authorTokenToPrint,
      // The live instance (eject-bake reuse): readOverlay/clearOverlay
      // without a second resolve round trip.
      'bake': bake,
    };
  }

  // ── the Live Overlay eject bake (edit redesign, decision 7, 2026-09-11) ─

  /// Reads the design's live overlay row (the author's text + image edits
  /// that streamed to client dials since the last eject). Null = no row.
  Future<Map<String, dynamic>?> readOverlay(String designId) async {
    final r = await _req('GET',
        'arxa_dial_overlays?design_id=eq.$designId&select=patches,rev');
    if (r.$1 >= 300) return null;
    final rows = jsonDecode(r.$2);
    if (rows is! List || rows.isEmpty || rows.first is! Map) return null;
    final patches = (rows.first as Map)['patches'];
    if (patches is! Map || patches.isEmpty) return null;
    return Map<String, dynamic>.from(patches);
  }

  /// Clears the overlay row (save_overlay with empty patches = revert):
  /// called by the eject AFTER every patch baked into source, so live
  /// view and source converge at the deploy boundary.
  Future<bool> clearOverlay(String designId) async {
    final r = await _req('POST', 'rpc/save_overlay', body: {
      'p_design_id': designId,
      'p_link_token': '',
      'p_base_rev': 0x7fffffff, // never stale on a deliberate clear
      'p_patches': {},
    });
    if (r.$1 >= 300) return false;
    final decoded = jsonDecode(r.$2);
    return decoded is Map && decoded['ok'] == true;
  }
}
