// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `runtime`, `spawn_session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Parse the QR payload and start dialing. Returns immediately with a live
/// handle; progress arrives on [`TransportSession::status_stream`].
///
/// * `qr_payload` — `arxa-pair:<base32(json)>` exactly as scanned.
/// * `device_name` — shown in the desktop's paired-devices list; defaults to
///   the device hostname / iPhone model.
TransportSession connect({required String qrPayload, String? deviceName}) =>
    RustLib.instance.api.crateApiConnect(
      qrPayload: qrPayload,
      deviceName: deviceName,
    );

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransportSession>>
abstract class TransportSession implements RustOpaqueInterface {
  /// Tear the session down: closes the QUIC connection, aborts the
  /// loopback proxy, releases the endpoint. Terminal for this handle
  /// (state becomes Disconnected; `resume()` on a closed handle redials
  /// only if a pairing is still held).
  void close();

  /// Loopback proxy port while Connected (`http://127.0.0.1:<port>/`),
  /// otherwise None. May change across reconnects — re-read it on every
  /// transition to Connected.
  int? get proxyPort;

  /// Register the OS push token (platform: `apns` | `fcm`). Stored for the
  /// session and re-sent over the tunnel after every (re)connect; if the
  /// tunnel is up now, it is sent immediately.
  void registerPushToken({required String platform, required String token});

  /// Redial after the app returns to the foreground. iOS suspends QUIC
  /// sockets in the background, so the old connection is usually dead on
  /// resume — this supersedes it and dials on the reconnect budget (5
  /// attempts, 3s backoff). No-op if the pairing was revoked or the
  /// session already closed without a stored pairing.
  void resume();

  /// Current state, for polling; prefer [`status_stream`].
  TransportState get state;

  /// Subscribe to lifecycle updates. Emits the current state immediately,
  /// then every transition. Multiple subscribers are fine.
  Stream<TransportState> statusStream();
}

/// Session lifecycle as observed from Dart. Mirrors
/// `transport::TransportState` (kept separate so the core stays FRB-free).
enum TransportState {
  connecting,
  connected,
  reconnecting,

  /// Desktop refused the token (or revoked it mid-session). Terminal —
  /// the user must scan a fresh QR code.
  revoked,

  /// Dial budget exhausted or `close()` called. `resume()` can redial.
  disconnected,
}
