// emit_playground — Dart port of tools/vendor/emit_playground/emit_playground.py.
//
// Renders each screen of the design/new React+Babel playground to a
// chrome-stripped, self-contained static HTML surface at
// design/new/surfaces/<surface>.html, for the freeze gate.
//
// Browser automation uses CDP (Chrome DevTools Protocol) via cdp.dart instead
// of Playwright. A dart:io HttpServer serves the design/ directory statically,
// replacing Python's http.server.SimpleHTTPRequestHandler.
//
// Exit discipline: 0 = every emitted surface rendered error-free ·
// 1 = missing producer files / parse errors / render or extraction failure /
//    drift in --check mode · 2 = environment (no Chrome).

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:appboxd/cdp.dart';
import 'package:path/path.dart' as p;

// ── constants (ported verbatim from emit_playground.py) ───────────────

/// The screen-content root inside the playground's iPhone frame: everything
/// outside it (stage, toolbar, frame hardware) is chrome by construction;
/// chrome INSIDE it (fake status bar, HUD overlays) is stripped via the
/// exclusions.json selectors.
const contentRoot = '.phone-screen';

/// Standalone HTML document template — tokens.css + app.css inlined as two
/// separate <style> blocks, assets rewritten, timestamp-free GENERATED banner.
const docTemplate = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
__BANNER__
<title>__SURFACE__</title>
<style>
__TOKENS__
</style>
<style>
__APPCSS__
</style>
</head>
<body>
__CONTENT__
</body>
</html>
''';

/// DOM extraction function — runs in the browser via CDP Runtime.evaluate.
/// Copies .phone-screen outerHTML, strips exclusion selectors, returns the
/// result. Copied verbatim from the Python source.
const extractJs = r'''(args) => {
  const root = document.querySelector(args.root);
  if (!root) return { ok: false, error: 'screen-content root not found: ' + args.root };
  const clone = root.cloneNode(true);
  for (const sel of args.selectors) {
    let hits;
    try { hits = clone.querySelectorAll(sel); }
    catch (e) { return { ok: false, error: 'bad exclusion selector ' + JSON.stringify(sel) + ' — ' + e }; }
    hits.forEach(n => n.remove());
  }
  return { ok: true, html: clone.outerHTML };
}''';

// ── text helpers ──────────────────────────────────────────────────────

/// Generated banner — timestamp-free, names the source screen.
String banner(String screenId, String role) {
  return '<!-- GENERATED by stacked_kit/tools/emit_playground — do not hand-edit. '
      "Source: design/new/index.html screen '$screenId' (role '$role'). -->";
}

/// Strip /* ... */ comments from CSS.
///
/// CSS comments carry no styling; dropping them keeps freeze chrome
/// signatures (e.g. 'tweak' inside a comment) out of emitted surfaces.
String stripCssComments(String css) {
  return css.replaceAll(RegExp(r'/\*.*?\*/', dotAll: true), '');
}

/// Repoint `src="assets/...` and `href="assets/...` at `../assets/`.
///
/// surfaces/ lives INSIDE the new/ producer folder, so assets/ is one level
/// up. Mirrors the Python's single regex: (src|href)="assets/ → ../assets/.
String rewriteAssets(String html) {
  return html.replaceAllMapped(
    RegExp(r'((?:src|href))="assets/'),
    (m) => '${m[1]}="../assets/',
  );
}

/// Allowed role for a registry entry.
///
/// entry.roles[0] wins; otherwise the role whose window.P2.roles shells
/// contain the entry's shell. Liberal about roles shape: {id: {shells:[...]}}
/// or {id: [...]} or [{id, shells}].
String? roleFor(Map<String, dynamic> entry, dynamic roles) {
  final r = entry['roles'];
  if (r is List && r.isNotEmpty) return r[0].toString();

  final shell = entry['shell']?.toString();
  // Build (roleId, shells) pairs from whatever shape roles has. LinkedHashMap
  // preserves insertion order so the first-wins fallback is deterministic.
  final pairs = <(String, List)>[];
  if (roles is Map) {
    for (final e in roles.entries) {
      final cfg = e.value;
      List shells;
      if (cfg is Map) {
        final s = cfg['shells'];
        shells = s is List ? s : [];
      } else if (cfg is List) {
        shells = cfg;
      } else {
        shells = [];
      }
      pairs.add((e.key.toString(), shells));
    }
  } else if (roles is List) {
    for (final cfg in roles) {
      if (cfg is Map) {
        final rid = cfg['id']?.toString();
        if (rid == null) continue;
        final s = cfg['shells'];
        pairs.add((rid, s is List ? s : []));
      }
    }
  }
  if (shell != null) {
    for (final pair in pairs) {
      if (pair.$2.any((s) => s.toString() == shell)) return pair.$1;
    }
  }
  return pairs.isNotEmpty ? pairs.first.$1 : null;
}

// ── static file server (replaces Python's http.server) ────────────────

ContentType _mimeFor(String ext) => switch (ext) {
      '.html' || '.htm' => ContentType.html,
      '.css' => ContentType('text', 'css'),
      '.js' || '.mjs' || '.jsx' => ContentType('application', 'javascript'),
      '.json' || '.map' => ContentType('application', 'json'),
      '.svg' => ContentType('image', 'svg+xml'),
      '.png' => ContentType('image', 'png'),
      '.jpg' || '.jpeg' => ContentType('image', 'jpeg'),
      '.gif' => ContentType('image', 'gif'),
      '.webp' => ContentType('image', 'webp'),
      '.ico' => ContentType('image', 'x-icon'),
      '.woff' => ContentType('font', 'woff'),
      '.woff2' => ContentType('font', 'woff2'),
      '.ttf' => ContentType('font', 'ttf'),
      '.otf' => ContentType('font', 'otf'),
      '.eot' => ContentType('application', 'vnd.ms-fontobject'),
      _ => ContentType.binary,
    };

/// Serve a file to the response stream, setting its content type.
Future<void> _serveFile(HttpRequest request, String path) async {
  request.response.headers.contentType = _mimeFor(p.extension(path).toLowerCase());
  try {
    await File(path).openRead().pipe(request.response);
  } catch (_) {
    try {
      await request.response.close();
    } catch (_) {}
  }
}

/// Start a static file server serving [rootDir] on an ephemeral loopback port.
///
/// Replaces Python's `http.server.SimpleHTTPRequestHandler` with
/// `directory=str(design)`. Resolves directory requests to index.html.
Future<HttpServer> startStaticServer(String rootDir) async {
  final server = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
  final rootAbs = p.normalize(rootDir);
  // ignore: unawaited_futures
  server.serveRequests((request) async {
    try {
      final reqPath = request.uri.path;
      final rel = p.posix.normalize(
        reqPath.startsWith('/') ? reqPath.substring(1) : reqPath,
      );
      final fsPath = p.join(rootAbs, rel);
      if (!p.isWithin(rootAbs, fsPath)) {
        request.response.statusCode = HttpStatus.forbidden;
        await request.response.close();
        return;
      }
      final type = FileSystemEntity.typeSync(fsPath);
      if (type == FileSystemEntityType.file) {
        await _serveFile(request, fsPath);
        return;
      }
      if (type == FileSystemEntityType.directory) {
        final idx = p.join(fsPath, 'index.html');
        if (FileSystemEntity.typeSync(idx) == FileSystemEntityType.file) {
          await _serveFile(request, idx);
          return;
        }
      }
      request.response.statusCode = HttpStatus.notFound;
      await request.response.close();
    } catch (_) {
      try {
        await request.response.close();
      } catch (_) {}
    }
  });
  return server;
}

/// Always tear the server down — success, failure, or exception.
Future<void> stopStaticServer(HttpServer? server) async {
  if (server == null) return;
  await server.close(force: true);
}

// ── main entry point ──────────────────────────────────────────────────

/// Render every registry surface of the design/new playground.
///
/// [designRoot] is the design directory — it must contain a `new/` subfolder
/// with index.html, tokens.css, app.css, and exclusions.json. It is served
/// over HTTP so the playground's asset references resolve.
///
/// Returns 0 on success, 1 on failure, 2 on environment error (no Chrome).
Future<int> emitPlayground(String designRoot, {bool check = false}) async {
  // EMIT_RENDER=skip — hermetic/CI bypass.
  if (Platform.environment['EMIT_RENDER'] == 'skip') {
    print('  (emit SKIPPED — EMIT_RENDER=skip; no surfaces written '
        '— hermetic/CI runs only)');
    return 0;
  }

  final newDir = p.join(designRoot, 'new');

  // ── validate required files ──
  for (final name in const [
    'index.html',
    'tokens.css',
    'app.css',
    'exclusions.json',
  ]) {
    final f = File(p.join(newDir, name));
    if (!f.existsSync()) {
      stderr.writeln('FAIL: missing ${p.relative(f.path, from: designRoot)} — '
          'the playground (new/index.html + tokens.css + app.css) '
          'and exclusions.json must exist');
      return 1;
    }
  }

  // ── read exclusions ──
  List selectors;
  try {
    final excl = jsonDecode(File(p.join(newDir, 'exclusions.json')).readAsStringSync())
        as Map<String, dynamic>;
    final raw = excl['selectors'];
    if (raw != null && raw is! List) {
      throw const FormatException('"selectors" must be a list');
    }
    selectors = (raw as List?) ?? const [];
  } catch (e) {
    stderr.writeln('FAIL: design/new/exclusions.json does not parse — $e');
    return 1;
  }

  final tokens = stripCssComments(
    File(p.join(newDir, 'tokens.css')).readAsStringSync(),
  );
  final appcss = stripCssComments(
    File(p.join(newDir, 'app.css')).readAsStringSync(),
  );

  final failures = <String>[];
  final seen = <String, String>{};
  final drifted = <String>[];
  final orphans = <String>[];
  var rendered = 0;

  HttpServer? server;
  try {
    server = await startStaticServer(designRoot);
    final port = server.port;
    final base = 'http://127.0.0.1:$port/new/index.html';

    // ── launch Chrome ──
    CdpClient client;
    try {
      client = await CdpClient.launch();
    } catch (e) {
      stderr.writeln('emit: ERROR (exit 2) — could not launch Chrome: $e');
      return 2;
    }

    try {
      // ── load registry from the playground ──
      final regTab = await client.newTab();
      await regTab.enable();
      await regTab.setViewport(390, 844, mobile: true);
      await regTab.navigateAndSettle(base, settleMs: 1500);

      for (final m in [...regTab.consoleErrors, ...regTab.pageErrors]) {
        failures.add('registry load: $m');
      }

      final registry =
          await regTab.evaluate('(window.P2 && window.P2.registry) || null');
      final roles =
          await regTab.evaluate('(window.P2 && window.P2.roles) || null');

      try {
        await client.send('Target.closeTarget', {'targetId': regTab.targetId});
      } catch (_) {}

      if (registry == null) {
        stderr.writeln('FAIL: window.P2.registry not found on '
            'design/new/index.html — the playground must expose the screen '
            'registry (array of {id, shell, roles, surface, ...}) as '
            'window.P2.registry');
        return 1;
      }
      if (registry is! List) {
        stderr.writeln(
            'FAIL: window.P2.registry is not an array of screen entries');
        return 1;
      }

      // ── render each surfaced screen ──
      for (final entry in registry) {
        if (entry is! Map<String, dynamic>) continue;
        final surface = entry['surface']?.toString();
        // registry-null screens are playground-only, never emitted.
        if (surface == null || surface.isEmpty) continue;
        final sid = entry['id']?.toString() ?? '';

        if (seen.containsKey(surface)) {
          failures.add("surface collision: '$surface' claimed by both "
              "'${seen[surface]}' and '$sid'");
          continue;
        }
        seen[surface] = sid;

        final role = roleFor(entry, roles);
        if (role == null) {
          failures.add("$surface: no usable role for screen '$sid' "
              '(entry.roles empty and no window.P2.roles shell match)');
          continue;
        }

        final url = Uri(
          scheme: 'http',
          host: '127.0.0.1',
          port: port,
          path: '/new/index.html',
          queryParameters: {'role': role, 'screen': sid},
        ).toString();

        // Fresh tab per surface — isolation matches the Python fresh_page().
        final tab = await client.newTab();
        await tab.enable();
        await tab.setViewport(390, 844, mobile: true);

        Map<String, dynamic>? res;
        try {
          await tab.navigateAndSettle(url, settleMs: 1500);
          res = (await tab.evaluateFunction(extractJs, {
            'root': contentRoot,
            'selectors': selectors,
          })) as Map<String, dynamic>?;
        } catch (e) {
          failures.add('$surface: render/extraction error — $e');
        }

        for (final m in [...tab.consoleErrors, ...tab.pageErrors]) {
          failures.add('$surface: console/page error — $m');
        }

        try {
          await client.send('Target.closeTarget', {'targetId': tab.targetId});
        } catch (_) {}

        if (res == null) continue;
        if (res['ok'] != true) {
          failures.add("$surface: ${res['error'] ?? 'extraction failed'}");
          continue;
        }

        // ── compose standalone doc ──
        final content = rewriteAssets(res['html'] as String);
        final doc = docTemplate
            .replaceAll('__BANNER__', banner(sid, role))
            .replaceAll('__SURFACE__', surface)
            .replaceAll('__TOKENS__', tokens)
            .replaceAll('__APPCSS__', appcss)
            .replaceAll('__CONTENT__', content);

        final outFile = File(p.join(newDir, 'surfaces', '$surface.html'));
        final rel = 'design/new/surfaces/$surface.html';

        if (check) {
          if (!outFile.existsSync()) {
            drifted.add('$surface.html');
            print('DRIFT $rel (not on disk — run emit)');
          } else if (outFile.readAsStringSync() != doc) {
            drifted.add('$surface.html');
            print('DRIFT $rel (playground changed — re-run emit)');
          } else {
            print('in-sync $rel');
          }
        } else {
          outFile.parent.createSync(recursive: true);
          if (outFile.existsSync() && outFile.readAsStringSync() == doc) {
            print('unchanged $rel (write-on-diff: content identical)');
          } else {
            outFile.writeAsStringSync(doc);
            print("wrote $rel  (screen '$sid', role '$role')");
          }
        }
        rendered++;
      }
    } finally {
      await client.close();
    }
  } finally {
    await stopStaticServer(server);
  }

  // ── orphan check (check mode only, informational) ──
  if (check) {
    final sdir = Directory(p.join(newDir, 'surfaces'));
    if (sdir.existsSync()) {
      final files = sdir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.html'))
          .toList()
        ..sort((a, b) => p.basename(a.path).compareTo(p.basename(b.path)));
      for (final f in files) {
        final stem = p.basenameWithoutExtension(f.path);
        if (!seen.containsKey(stem)) {
          orphans.add(p.basename(f.path));
          print('  note: orphan surface ${p.basename(f.path)} '
              '(no registry entry — left alone)');
        }
      }
    }
  }

  // ── summary ──
  for (final f in failures) {
    stderr.writeln('FAIL: render: $f');
  }
  if (drifted.isNotEmpty) {
    stderr.writeln('FAIL: emit --check: ${drifted.length} surface(s) drifted '
        '(re-run emit): ${drifted.join(', ')}');
  }
  if (failures.isNotEmpty || drifted.isNotEmpty) {
    return 1;
  }
  if (check) {
    print('emit --check: PASS — $rendered surface(s) in-sync, '
        '${orphans.length} orphan(s) noted');
  } else {
    print('emit: PASS — $rendered surface(s) emitted to '
        '${p.join(newDir, 'surfaces')}/');
  }
  return 0;
}
