// emit_htmx — Dart port of tools/vendor/emit_htmx/emit_htmx.py (631 lines).
//
// Renders each screen of an htmx producer to a chrome-stripped, self-contained
// static HTML surface at <design-root>/surfaces/<surface>.html.
//
// Browser automation uses CDP (Chrome DevTools Protocol) via cdp.dart instead
// of Playwright. The node producer server is unchanged — only the browser
// driver is replaced.
//
// Exit discipline: 0 = success · 1 = fail · 2 = environment.
//   - 2: design root missing, no node, Chrome missing, server won't boot
//   - 1: missing producer files, parse errors, render/extraction failures,
//         drift in --check mode

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:appboxd/cdp.dart';
import 'package:path/path.dart' as p;

// ── constants (ported verbatim from emit_htmx.py) ─────────────────────

/// CSS the producer links from ui/common/base.html, in that order.
const cssFiles = ['fonts.css', 'tokens.css', 'app.css', 'hda.css'];

/// The screen-content root inside the htmx stage's iPhone frame: everything
/// outside it (stage, toolbar, phone hardware) is chrome by construction;
/// chrome INSIDE it (dynamic island, status bar, home indicator) is stripped
/// via the shared exclusions.json selectors.
const contentRoot = '.phone-screen';

/// stage_viewmodel renders the Phase-E placeholder when the requested role
/// cannot see the surface. It returns 200 with a clean console, so only this
/// copy distinguishes it from a real surface.
const placeholderMark = 'Phase E surface —';

/// How the emitted surface reaches the producer's assets from surfaces/.
const assetPrefix = '../assets/';

/// Standalone HTML document template — CSS inlined as <style>, assets
/// rewritten, timestamp-free GENERATED banner.
const docTemplate = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" href="data:,">
__BANNER__
<title>__SURFACE__</title>
<style>
__CSS__
</style>
</head>
<body>
__CONTENT__
</body>
</html>
''';

/// DOM extraction function — runs in the browser via CDP Runtime.evaluate.
/// Copies .phone-screen outerHTML, strips exclusion selectors, reports label
/// and placeholder status. Copied verbatim from the Python source.
const extractJs = r'''(args) => {
  const root = document.querySelector(args.root);
  if (!root) return { ok: false, error: 'screen-content root not found: ' + args.root };
  const label = root.getAttribute('data-screen-label');
  const placeholder = root.innerHTML.includes(args.placeholderMark);
  const clone = root.cloneNode(true);
  for (const sel of args.selectors) {
    let hits;
    try { hits = clone.querySelectorAll(sel); }
    catch (e) { return { ok: false, error: 'bad exclusion selector ' + JSON.stringify(sel) }; }
    hits.forEach(n => n.remove());
  }
  return { ok: true, html: clone.outerHTML, label: label, placeholder: placeholder };
}''';

// ── text helpers ──────────────────────────────────────────────────────

/// Generated banner — timestamp-free, names the source screen.
String banner(String screenId, String role) {
  return '<!-- GENERATED by appboxd/emit_htmx — do not hand-edit. '
      "Source: htmx producer screen '$screenId' (role '$role'). -->";
}

/// Strip /* ... */ comments from CSS.
String stripCssComments(String css) {
  return css.replaceAll(RegExp(r'/\*.*?\*/', dotAll: true), '');
}

/// Repoint every absolute /assets/... URL at the producer tree.
///
/// Per-URL-context, not a blanket string replace, so prose that merely
/// contains the characters `/assets/` is never silently altered.
String rewriteAssets(String text) {
  // Double-quoted attribute values: src="/assets/…", href=, poster=, …
  text = text.replaceAllMapped(
    RegExp(r'((?:src|href|poster|srcset|data-src|content)=")/assets/'),
    (m) => '${m[1]}$assetPrefix',
  );
  // Single-quoted attribute values
  text = text.replaceAllMapped(
    RegExp(r"((?:src|href|poster|srcset|data-src|content)=')/assets/"),
    (m) => "${m[1]}$assetPrefix",
  );
  // CSS url() in stylesheets and inline style attributes, quoted or bare
  text = text.replaceAllMapped(
    RegExp(r'''url\((["']?)/assets/'''),
    (m) => 'url(${m[1]}$assetPrefix',
  );
  // srcset lists carry further ", /assets/… 2x" entries after the first
  text = text.replaceAllMapped(
    RegExp(r'(,\s*)/assets/'),
    (m) => '${m[1]}$assetPrefix',
  );
  return text;
}

/// Fail loudly on any /assets/ URL the rewrite did not reach, AND on any
/// rewritten URL that does not resolve on disk.
///
/// A missed URL is a silently broken surface (404 image, unstyled font),
/// which is exactly what a freeze gate exists to catch — so it is a hard
/// failure, never a warning.
void assertAssetsRewritten(
  String where,
  String text,
  List<String> failures, {
  String? surfacesDir,
}) {
  final leftoverRe = RegExp(r'''[("'=]\s*/assets/[^)"'\s>]*''');
  final leftovers = leftoverRe
      .allMatches(text)
      .map((m) => m.group(0)!)
      .toSet()
      .toList()
    ..sort();
  if (leftovers.isNotEmpty) {
    failures.add('$where: ${leftovers.length} un-rewritten /assets/ URL(s): '
        '${leftovers.take(4).map((x) => x.trim()).join(', ')}');
  }

  if (surfacesDir == null) return;

  final rewrittenRe = RegExp(r'''[("'=]\s*(\.\./assets/[^)"'\s>]*)''');
  final urls = rewrittenRe
      .allMatches(text)
      .map((m) => m.group(1)!)
      .toSet()
      .toList()
    ..sort();
  final missing = <String>[];
  for (final url in urls) {
    final clean = url.split('?').first.split('#').first;
    final path = p.normalize(p.join(surfacesDir, clean));
    if (!File(path).existsSync()) missing.add(url);
  }
  if (missing.isNotEmpty) {
    failures.add('$where: ${missing.length} rewritten asset URL(s) do not resolve '
        '(relative to $surfacesDir): ${missing.take(4).join(', ')}');
  }
}

/// Which persona actually sees this surface.
///
/// Mirrors scripts/seed/sweep_htmx_routes.mjs's roleFor — the htmx tree has
/// no window.P2.roles table to consult, the role is derived from the registry
/// entry itself.
String roleFor(Map<String, dynamic> entry) {
  final roles = entry['roles'];
  if (roles is List && roles.isNotEmpty) return roles[0].toString();
  final comp = (entry['comp'] ?? '').toString();
  if (comp.startsWith('Studio')) return 'leo';
  if (comp.startsWith('Admin')) return 'erika';
  return 'felix';
}

// ── server boot / teardown ────────────────────────────────────────────

/// Bind an ephemeral port on loopback and return it.
Future<int> freePort() async {
  final s = await ServerSocket.bind(InternetAddress.loopbackIPv4, 0);
  final port = s.port;
  await s.close();
  return port;
}

/// The producer server could not be started — an environment fault.
class ServerBootError implements Exception {
  final String message;
  ServerBootError(this.message);
  @override
  String toString() => message;
}

bool _nodeOnPath() {
  try {
    return Process.runSync('node', ['--version']).exitCode == 0;
  } catch (_) {
    return false;
  }
}

/// Resolve frozen_clock.mjs: check designRoot first (the producer tree may
/// bundle it), then walk up to find tools/vendor/emit_htmx/frozen_clock.mjs
/// at the repo root.
String? _resolveClockPath(String htmxDir) {
  final local = File(p.join(htmxDir, 'frozen_clock.mjs'));
  if (local.existsSync()) return local.path;

  var dir = Directory(htmxDir);
  for (var i = 0; i < 20; i++) {
    final candidate =
        File(p.join(dir.path, 'tools', 'vendor', 'emit_htmx', 'frozen_clock.mjs'));
    if (candidate.existsSync()) return candidate.path;
    final parent = dir.parent;
    if (parent.path == dir.path) break; // filesystem root
    dir = parent;
  }
  return null;
}

/// Read viewport from config/app-box.config.json, fallback to 390×844.
(int, int) _cfgViewport(String htmxDir) {
  try {
    var dir = Directory(htmxDir);
    for (var i = 0; i < 20; i++) {
      final cfg = File(p.join(dir.path, 'config', 'app-box.config.json'));
      if (cfg.existsSync()) {
        final d = jsonDecode(cfg.readAsStringSync()) as Map<String, dynamic>;
        final v =
            (d['viewports'] as Map<String, dynamic>)['mobile'] as Map<String, dynamic>;
        return ((v['width'] as num).toInt(), (v['height'] as num).toInt());
      }
      final parent = dir.parent;
      if (parent.path == dir.path) break;
      dir = parent;
    }
  } catch (_) {}
  return (390, 844);
}

/// Start the htmx producer on [port] and wait for its ready line.
///
/// Readiness is the server's OWN stdout announcement, not a TCP poll: a poll
/// cannot tell "not listening yet" from "died on import", and the common
/// failure here IS death on import (node_modules is gitignored).
Future<Process> bootServer(
  String htmxDir,
  int port, {
  Map<String, String>? extraEnv,
}) async {
  if (!_nodeOnPath()) {
    throw ServerBootError(
        'no `node` on PATH — the htmx producer is a node server');
  }

  final env = Map<String, String>.from(Platform.environment)
    ..['PORT'] = port.toString();
  if (extraEnv != null) env.addAll(extraEnv);

  final clock = _resolveClockPath(htmxDir);
  final args = <String>[
    if (clock != null) ...['--import', Uri.file(clock).toString()],
    'server.js',
  ];

  final proc = await Process.start('node', args,
      workingDirectory: htmxDir, environment: env);

  final outLines = <String>[];
  final errLines = <String>[];
  final ready = Completer<void>();

  proc.stdout
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen((line) {
    outLines.add(line);
    if (line.contains('http://localhost:') && !ready.isCompleted) {
      ready.complete();
    }
  });
  proc.stderr
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen(errLines.add);

  try {
    final result = await Future.any<String>([
      ready.future.then((_) => 'ready'),
      proc.exitCode.then((c) => 'exit:$c'),
    ]).timeout(const Duration(seconds: 30));

    if (result == 'ready') return proc;

    // Process exited before becoming ready.
    final code = int.parse(result.substring(5));
    await stopServer(proc);
    final src = errLines.isNotEmpty ? errLines : outLines;
    final start = src.length < 12 ? 0 : src.length - 12;
    final tail = src.skip(start).join().trim();
    throw ServerBootError(
      'server.js exited with code $code before becoming ready.\n'
      '  cwd: $htmxDir\n'
      '  stderr:\n${tail.isEmpty ? '(no output)' : tail}\n'
      '  (node_modules is gitignored — try `npm install` there)',
    );
  } on TimeoutException {
    await stopServer(proc);
    throw ServerBootError(
        'server.js did not print a ready line within 30s (cwd: $htmxDir)');
  }
}

/// Always tear the server down — success, failure, or exception.
Future<void> stopServer(Process? proc) async {
  if (proc == null) return;
  proc.kill(ProcessSignal.sigterm);
  try {
    await proc.exitCode.timeout(const Duration(seconds: 5));
  } on TimeoutException {
    proc.kill(ProcessSignal.sigkill);
    await proc.exitCode;
  }
}

// ── main entry point ─────────────────────────────────────────────────

/// Boot the producer, render every registry surface, write on diff.
///
/// [designRoot] is the htmx producer directory — it must contain server.js,
/// models/screens_model/registry.json, exclus.json, and assets/css/*.css.
///
/// Returns 0 on success, 1 on failure, 2 on environment error.
Future<int> emitHtmx(String designRoot, {bool check = false}) async {
  // EMIT_RENDER=skip — hermetic/CI bypass.
  if (Platform.environment['EMIT_RENDER'] == 'skip') {
    print('  (emit SKIPPED — EMIT_RENDER=skip; no surfaces written '
        '— hermetic/CI runs only)');
    return 0;
  }

  if (!Directory(designRoot).existsSync()) {
    stderr.writeln('emit: ERROR (exit 2) — design root not found: $designRoot');
    return 2;
  }

  final registryPath =
      p.join(designRoot, 'models', 'screens_model', 'registry.json');
  final exclusionsPath = p.join(designRoot, 'exclusions.json');
  final serverPath = p.join(designRoot, 'server.js');

  // ── validate required files ──
  final required = <String>[
    serverPath,
    registryPath,
    exclusionsPath,
    for (final name in cssFiles) p.join(designRoot, 'assets', 'css', name),
  ];
  for (final req in required) {
    if (!File(req).existsSync()) {
      stderr.writeln('FAIL: missing $req — the htmx producer '
          '(server.js + models/screens_model/registry.json + '
          'assets/css/*.css) and exclusions.json must exist');
      return 1;
    }
  }

  // ── read exclusions ──
  List selectors;
  try {
    final excl =
        jsonDecode(File(exclusionsPath).readAsStringSync()) as Map<String, dynamic>;
    final raw = excl['selectors'];
    if (raw != null && raw is! List) {
      throw const FormatException('"selectors" must be a list');
    }
    selectors = (raw as List?) ?? [];
  } catch (e) {
    stderr.writeln('FAIL: exclusions.json does not parse: $e');
    return 1;
  }

  // ── read registry ──
  List registry;
  try {
    registry = jsonDecode(File(registryPath).readAsStringSync()) as List;
    if (registry.isEmpty) {
      throw const FormatException('registry.json must be a non-empty array');
    }
  } catch (e) {
    stderr.writeln('FAIL: $registryPath does not parse: $e');
    return 1;
  }

  // ── read + rewrite CSS ──
  final failures = <String>[];
  final cssParts = <String>[];
  for (final name in cssFiles) {
    final raw = stripCssComments(
        File(p.join(designRoot, 'assets', 'css', name)).readAsStringSync());
    cssParts.add(rewriteAssets(raw));
  }
  final css = cssParts.join('\n');
  assertAssetsRewritten('inlined CSS', css, failures);

  final outdir = p.join(designRoot, 'surfaces');
  final (vw, vh) = _cfgViewport(designRoot);

  Process? proc;
  var rendered = 0;
  final skipped = <String>[];
  final drifted = <String>[];
  final seen = <String, String>{};

  // ── boot server ──
  try {
    final port = await freePort();
    try {
      proc = await bootServer(designRoot, port);
    } on ServerBootError catch (e) {
      stderr.writeln(
          'emit: ERROR (exit 2) — could not boot the htmx producer: $e');
      return 2;
    }

    // ── launch Chrome ──
    CdpClient client;
    try {
      client = await CdpClient.launch();
    } catch (e) {
      stderr.writeln('emit: ERROR (exit 2) — could not launch Chrome: $e');
      return 2;
    }

    try {
      for (final entry in registry) {
        if (entry is! Map<String, dynamic>) continue;

        final sid = entry['id']?.toString() ?? '';
        final surface = entry['surface']?.toString();

        if (surface == null || surface.isEmpty) {
          // NULL-SURFACE RULE: skipped, never invented, always REPORTED.
          skipped.add(sid);
          print("skip: screen '$sid' — registry surface is null "
              '(no canonical surface name to emit under)');
          continue;
        }

        if (seen.containsKey(surface)) {
          failures.add("surface collision: '$surface' claimed by both "
              "'${seen[surface]}' and '$sid'");
          continue;
        }
        seen[surface] = sid;

        final role = roleFor(entry);
        final url = Uri(
          scheme: 'http',
          host: '127.0.0.1',
          port: port,
          path: '/',
          queryParameters: {'role': role, 'screen': sid},
        ).toString();

        // Fresh tab per surface — isolation matches the Python fresh_page().
        final tab = await client.newTab();
        await tab.enable();
        await tab.setViewport(vw, vh, mobile: true);

        Map<String, dynamic>? res;
        try {
          await tab.navigateAndSettle(url, settleMs: 1500);
          res = (await tab.evaluateFunction(extractJs, {
            'root': contentRoot,
            'selectors': selectors,
            'placeholderMark': placeholderMark,
          })) as Map<String, dynamic>?;
        } catch (e) {
          failures.add('$surface: render/extraction error — $e');
        }

        // Check console/page errors (captured by CdpSession.enable).
        for (final m in [...tab.consoleErrors, ...tab.pageErrors]) {
          failures.add('$surface: console/page error — $m');
        }

        // Close the tab regardless of extraction outcome.
        try {
          await client.send('Target.closeTarget', {'targetId': tab.targetId});
        } catch (_) {}

        if (res == null) continue;

        // ── validate extraction result ──
        if (res['ok'] != true) {
          failures.add("$surface: ${res['error'] ?? 'extraction failed'}");
          continue;
        }
        if (res['placeholder'] == true) {
          failures.add("$surface: role '$role' got the Phase-E placeholder, "
              "not the real surface for screen '$sid'");
          continue;
        }
        final wantLabel = '$role \u00b7 $sid';
        if (res['label'] != wantLabel) {
          failures.add("$surface: data-screen-label is '${res['label']}', "
              "expected '$wantLabel' — the surface template did not render");
          continue;
        }

        // ── compose standalone doc ──
        final content = rewriteAssets(res['html'] as String);
        assertAssetsRewritten(surface, content, failures, surfacesDir: outdir);

        final doc = docTemplate
            .replaceAll('__BANNER__', banner(sid, role))
            .replaceAll('__SURFACE__', surface)
            .replaceAll('__CSS__', css)
            .replaceAll('__CONTENT__', content);

        final outFile = File(p.join(outdir, '$surface.html'));
        final rel = 'surfaces/$surface.html';

        if (check) {
          if (!outFile.existsSync()) {
            drifted.add('$surface.html');
            print('DRIFT $rel (not on disk — run emit)');
          } else if (outFile.readAsStringSync() != doc) {
            drifted.add('$surface.html');
            print('DRIFT $rel (producer changed — re-run emit)');
          } else {
            print('in-sync $rel');
          }
        } else {
          outFile.parent.createSync(recursive: true);
          if (outFile.existsSync() && outFile.readAsStringSync() == doc) {
            print('unchanged $rel (write-on-diff: content identical)');
          } else {
            outFile.writeAsStringSync(doc);
            print("wrote $rel  (screen '$sid', role '$role')");
          }
        }
        rendered++;
      }
    } finally {
      await client.close();
    }
  } finally {
    await stopServer(proc);
  }

  // ── orphan check (check mode only, informational) ──
  if (check && Directory(outdir).existsSync()) {
    final files = Directory(outdir)
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.html'))
        .map((f) => p.basenameWithoutExtension(f.path))
        .toList()
      ..sort();
    for (final stem in files) {
      if (!seen.containsKey(stem)) {
        print('note: orphan surfaces/$stem.html (no registry surface claims it)');
      }
    }
  }

  // ── summary ──
  final skipTail = skipped.isNotEmpty
      ? ' (${skipped.length} registry-null screen(s) skipped: '
          '${skipped.join(', ')})'
      : '';

  if (failures.isNotEmpty) {
    stderr.writeln('emit: FAIL — ${failures.length} problem(s):');
    for (final f in failures) {
      stderr.writeln('  - $f');
    }
    return 1;
  }

  if (check) {
    if (drifted.isNotEmpty) {
      stderr.writeln('emit --check: FAIL — ${drifted.length} surface(s) drifted: '
          '${drifted.join(', ')}');
      return 1;
    }
    print('emit --check: PASS — $rendered surface(s) in-sync with surfaces/$skipTail');
    return 0;
  }

  print('emit: PASS — $rendered surface(s) emitted to surfaces/$skipTail');
  return 0;
}
