fn main() {
    // Declare app commands in the ACL manifest so permissions are autogenerated
    // (`allow-<kebab-command>`). Required because the studio UI is served from a
    // remote (localhost) origin: tauri only lets remote origins reach custom
    // commands that a `remote` capability explicitly grants (webview/mod.rs ACL
    // gate). Side effect: once an app manifest exists, local windows are gated
    // too — capabilities/default.json grants them for main + pair.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "studio_url",
            "open_studio",
            "open_pairing_window",
            "report_theme",
            "get_theme",
            "pairing_begin",
            "pairing_status",
            "pairing_revoke",
        ])),
    )
    .expect("failed to run tauri-build");
}
