import 'dart:convert';

/// The QR-pairing payload (12.3). The desktop encodes this into the QR; the
/// companion decodes it after scanning.
///
/// Carries: the desktop's [host] + [port] on the LAN, a single-use [nonce], and
/// the [fingerprint] of the desktop's ephemeral TLS key (which the companion
/// PINS — see [Fingerprint]). A relay that captures this QR and re-presents it
/// is defeated by the nonce lifecycle (single-use, rotating) in [PairingSession]
/// and the human confirm dialog — NOT by this payload's contents alone.
///
/// Format: versioned JSON. The QR is small (host + port + 32-byte nonce hex +
/// 64-char fp ≈ 130 chars), so JSON is debuggable over a bespoke binary encoding.
/// A `v` field lets the decoder reject an unknown future/past shape loudly
/// rather than misparsing.
class QrPayload {
  static const int version = 1;
  static const String _scheme = 'appbox-pair';

  final String host;
  final int port;
  final String nonce; // hex; single-use, generated by PairingSession
  final String fingerprint; // hex SHA-256 of the SPKI (Fingerprint.ofSpki)

  const QrPayload({
    required this.host,
    required this.port,
    required this.nonce,
    required this.fingerprint,
  });

  /// Encode to the QR string. `appbox-pair:<base64url(json)>` — the scheme prefix
  /// lets the OS route a scanned code to the companion (and lets a non-appbox QR
  /// be rejected at the parse step, not after handing attacker data to JSON).
  String encode() {
    final json = jsonEncode({
      'v': version,
      'host': host,
      'port': port,
      'n': nonce,
      'fp': fingerprint,
    });
    final b64 = base64Url.encode(utf8.encode(json)).replaceAll('=', '');
    return '$_scheme:$b64';
  }

  /// Decode a scanned QR string. Returns `null` for anything that is not an
  /// appbox-pair payload of a known version with all four fields present and
  /// well-typed. A payload that fails shape MUST return null, never throw — the
  /// scanner hands this attacker-influenced data.
  static QrPayload? tryParse(String raw) {
    final idx = raw.indexOf(':');
    if (idx < 0 || raw.substring(0, idx) != _scheme) return null;
    final b64 = raw.substring(idx + 1);
    String jsonStr;
    try {
      // re-pad (encode strips '='); base64Url refuses malformed input by throwing
      final pad = b64.length % 4 == 0 ? b64 : b64 + '=' * (4 - b64.length % 4);
      jsonStr = utf8.decode(base64Url.decode(pad));
    } on FormatException {
      return null;
    }
    Object decoded;
    try {
      decoded = jsonDecode(jsonStr);
    } on FormatException {
      return null;
    }
    if (decoded is! Map<String, dynamic>) return null;
    if (decoded['v'] != version) return null;
    final host = decoded['host'];
    final port = decoded['port'];
    final nonce = decoded['n'];
    final fp = decoded['fp'];
    if (host is! String ||
        port is! num ||
        nonce is! String ||
        fp is! String) {
      return null;
    }
    if (port < 0 || port > 65535) return null;
    if (host.isEmpty || nonce.isEmpty || fp.isEmpty) return null;
    return QrPayload(
      host: host,
      port: port.toInt(),
      nonce: nonce,
      fingerprint: fp,
    );
  }

  @override
  String toString() =>
      'QrPayload(host: $host, port: $port, nonce: $nonce, fp: $fingerprint)';
}
