/// Generates a Postgres/Supabase migration from [KitTableSchema]
/// descriptors. Pure Dart — no `flutter` imports — so it runs under
/// `dart run` outside the Flutter toolchain (see `example/generate.dart`).
library;

import '../schema/kit_schema_topology.dart';
import '../schema/kit_table_schema.dart';

/// Emits one `create table if not exists` migration per schema, ordered so
/// that a table referenced by another table's `reference` column is created
/// first ([topologicalSchemaOrder]).
class KitSupabaseSqlEmitter {
  /// Renders [schemas] into a single migration SQL string.
  ///
  /// Throws [ArgumentError] if two or more distinct tables in [schemas]
  /// reference each other in a cycle — plain `create table` statements
  /// cannot satisfy that ordering (a self-referencing table is fine and is
  /// not treated as a cycle).
  String emit(List<KitTableSchema> schemas) {
    final ordered = topologicalSchemaOrder(schemas);

    final buffer = StringBuffer()
      ..writeln(
        '-- Generated by appbox_kit_data (KitSupabaseSqlEmitter). Do not edit by hand.',
      )
      ..writeln(
        "-- note: Row Level Security policies and grants are the operator's responsibility; none are emitted here.",
      )
      ..writeln();

    for (final schema in ordered) {
      buffer.writeln('create table if not exists "${schema.table}" (');
      buffer.writeln(
        schema.columns.map(_columnLine).join(',\n'),
      );
      buffer.writeln(');');
      buffer.writeln();
    }

    return buffer.toString();
  }

  String _columnLine(KitColumn column) {
    final buffer = StringBuffer('  "${column.name}" ')..write(
        _columnType(column),
      );
    if (!column.nullable) {
      buffer.write(' not null');
    }
    return buffer.toString();
  }

  String _columnType(KitColumn column) {
    switch (column.type) {
      case KitColumnType.id:
        return 'uuid primary key';
      case KitColumnType.text:
        return 'text';
      case KitColumnType.integer:
        return 'bigint';
      case KitColumnType.real:
        return 'double precision';
      case KitColumnType.boolean:
        return 'boolean';
      case KitColumnType.timestamptz:
        return 'timestamptz';
      case KitColumnType.jsonb:
        return 'jsonb';
      case KitColumnType.reference:
        return 'uuid references "${column.references}"("id")';
    }
  }
}
