/// Generates a Supabase `seed.sql` from fixture rows and [KitTableSchema]
/// descriptors. Pure Dart — no `flutter` imports — so it runs under
/// `dart run` outside the Flutter toolchain (see `example/generate.dart`).
library;

import 'dart:convert';

import '../ids/kit_id_service.dart';
import '../schema/kit_schema_topology.dart';
import '../schema/kit_table_schema.dart';

/// Emits idempotent `insert ... on conflict ("id") do update` statements for
/// every fixture row, in the same dependency-first table order as
/// [KitSupabaseSqlEmitter].
///
/// SQL literal encoding here is a trust boundary: every value is escaped
/// explicitly (see [_encode]) — nothing is interpolated unescaped into the
/// output.
class KitSupabaseSeedEmitter {
  KitSupabaseSeedEmitter({required this.idService});

  final KitIdService idService;

  /// Renders `fixturesByTable` into a single seed SQL string, canonicalizing
  /// every row's `id` and reference columns via [idService] first.
  ///
  /// Throws [ArgumentError] if `schemasByTable`'s tables reference each
  /// other in a cycle (see [topologicalSchemaOrder]), or if a row is missing
  /// its `id` value (via [KitIdService.canonicalizeRow]).
  String emit({
    required Map<String, List<Map<String, dynamic>>> fixturesByTable,
    required Map<String, KitTableSchema> schemasByTable,
  }) {
    final ordered = topologicalSchemaOrder(schemasByTable.values.toList());

    final buffer = StringBuffer()
      ..writeln(
        '-- Generated by appbox_kit_data (KitSupabaseSeedEmitter). Do not edit by hand.',
      )
      ..writeln();

    for (final schema in ordered) {
      final rows = fixturesByTable[schema.table];
      if (rows == null || rows.isEmpty) continue;

      for (final rawRow in rows) {
        final row = idService.canonicalizeRow(schema, rawRow);
        buffer.writeln(_insertStatement(schema, row));
      }
      buffer.writeln();
    }

    return buffer.toString();
  }

  String _insertStatement(KitTableSchema schema, Map<String, dynamic> row) {
    final columnNames = <String>[];
    final values = <String>[];
    for (final column in schema.columns) {
      columnNames.add('"${column.name}"');
      values.add(_encode(column, row[column.name]));
    }

    final updates = schema.columns
        .where((c) => c.type != KitColumnType.id)
        .map((c) => '"${c.name}" = excluded."${c.name}"')
        .join(', ');

    final conflictClause =
        updates.isEmpty ? 'do nothing' : 'do update set $updates';

    return 'insert into "${schema.table}" (${columnNames.join(', ')}) '
        'values (${values.join(', ')}) '
        'on conflict ("id") $conflictClause;';
  }

  /// Encodes a single value as a SQL literal for [column]'s type. Absent
  /// (`null`) values always become `NULL`, regardless of type.
  String _encode(KitColumn column, dynamic value) {
    if (value == null) return 'NULL';

    switch (column.type) {
      case KitColumnType.id:
      case KitColumnType.reference:
      case KitColumnType.text:
      case KitColumnType.timestamptz:
        return _sqlString(value.toString());
      case KitColumnType.integer:
      case KitColumnType.real:
        return (value as num).toString();
      case KitColumnType.boolean:
        return (value as bool) ? 'true' : 'false';
      case KitColumnType.jsonb:
        return '${_sqlString(jsonEncode(value))}::jsonb';
    }
  }

  /// Single-quotes [raw], doubling embedded single quotes (`''`) per SQL
  /// string-literal escaping. This is the only place raw text becomes part
  /// of the emitted SQL.
  String _sqlString(String raw) => "'${raw.replaceAll("'", "''")}'";
}
